FirelyTeam/firely-net-sdk

src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs

Two of the unit tests included hard-coded references to c:/temp. As my machine has its temp directory elsewhere and there is a good .Net API to find the correct location, I have replaced the hard-coded references with code to correctly obtain the temp directory (and also use the Path.Combine API to append the filenames to it).
(this is a new cleaner version of pull request #152 )

Remove hard-coded references to c:/temp from unit tests

---

src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
src/Hl7.Fhir.Core/Properties/AssemblyInfo.cs
src/Hl7.Fhir.Specification/Properties/AssemblyInfo.cs

See issue #161 . This would cleanly declare that Fhir.Net is not CLS compliant. I.e. the Assembly is marked properly, and this also makes the suppression of the compiler warnings obsolete (the compiler only emits warnings CS3015 and 3016 when the assembly is declared to be CLS compliant).

Correctly declare CLS non-compliance.

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/Requester.cs

Unfortunately, I had overlooked that due to the rebuilt code, the LastResult was not being properly set anymore.
I have fixed the issue and added a dedicated integration test for status 500 response handling.
P.S.: I am wondering whether the Lastxxx properties in Requester.cs should exist? One could safely share the FhirClient between multiple threads otherwise, but it seems the Lastxxx properties will overwrite each other when FhirClient is invoked from multiple threads. But I guess that's a discussion for another day...

Fix for pull request #156

---

src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
src/Hl7.Fhir.Core/Introspection/ReferencesAttribute.cs
src/Hl7.Fhir.Core/Properties/AssemblyInfo.cs
src/Hl7.Fhir.Core/Validation/AllowedTypesAttribute.cs
src/Hl7.Fhir.Specification/Properties/AssemblyInfo.cs

Hl7.Fhir.Specification is fully CLSCompliant. I.e. assembly flagged as CLSCompliant true and no need to suppress any warnings.
Hl7.Fhir.Core: Mark the 2 offending classes specifically as non-compliant. Only suppress warning CS3016, as CS3015 no longer occurs. Mark overall assembly as CLSCompliant to receive warnings if VB case ambiguity is accidentally introduced.

Amendment to PR #162: Reenable VB case ambiguity warnings.

---

src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Portable45.Tests.csproj
src/Hl7.Fhir.Core.Tests/packages.config
src/Hl7.Fhir.Core/Hl7.Fhir.Core.Portable45.csproj
src/Hl7.Fhir.Core/packages.config
src/Hl7.Fhir.Portable45.sln

I wasn't as aware of strong naming yet when I submitted PR #165. I referenced a version of Portable.DataAnnotations which was not strong named.
A strong-named version of Portable.DataAnnotations is now available. This PR switches out references to Portable.DataAnnotations by Portable-Strong.DataAnnotations (also available through NuGet).

Use strong-named version of Portable.DataAnnotations.

---

src/Hl7.Fhir.Core/Rest/HttpUtil.cs
src/Hl7.Fhir.Core/Rest/Requester.cs

Changed the way we handle non-success http codes, a bit of refactoring to make the flow of the code cleaner.

Some clean-up of Requester non-success status handling

---

src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
src/Hl7.Fhir.Core/Rest/SearchParams.cs

All search parameter parsing errors cause a FormatException. The exception message specifies the name of the parameter that caused the error.
Specifying more than once a search parameter that can have only a single value now cause a parsing error – previously there was no error and all values except the last one were ignored.
Sort orders just starting with ‘asc’ or ‘desc’ – e.g. ‘desczzz’ or ‘ascdesc’ were considered valid, now they cause an error. ‘ascending’ and ‘descending’ and their truncations down to ‘asc’ and ‘desc’ are considered valid.
Empty generic search parameters no longer cause an error, and are added ‘as is’ to the SearchParams.Parameters collection. This allow the caller to ignore them or generate appropriate error messages depending on their meaning.
(Based on …

Search parameters parsing improvements

---

src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/MyBasic.structuredefinition.xml
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotElementBaseGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorEvents.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorSettings.cs

The SnapshotGenerator.PrepareElement provides a reference to the resolved base element definition.
The event arguments now also include a reference to the containing base structure definition.

Develop - snapshot generator - PrepareElement event also provides reference to base structure

---

src/Hl7.Fhir.Core/FluentPath/PocoElementNavigator.cs

Convert the FHIR PositiveInt type to a fluentpath compatible value (which is a long, not an int)
use case is that this fluentpath expression won't work due to a type incompatibility
"Patient.telecom.where(system = 'phone' and rank = 1).exists()"
1 is a **long** (Int64) in fluentpath, however the positiveInt is returned to fluentpath from the poconavigator as an **int** (Int32)

PocoElement Navigator positiveint type conversion

---

src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
src/Hl7.Fhir.Core/Model/Bundle.cs

The Bundle class is currently using the `Uri.ToString()` method to store the various links. The `Uri.ToString()` method does preserve URL encoding. According to the documentation, `Uri.ToString()` unescapes all characters except #, ?, and %.
For example if one were to set the SelfLink property to `http://foo/bar?p1=a%2Fb&p2=c%3Ad` and subsquently retrieved the value, the resulting `SelfLink.AbsoluteUri` and `SelfLink.OriginalString` property values would both then be `http://foo/bar?p1=a%2Fb&p2=c:d`. Note that the `%3A` gets decoded. We do not believe this to be the desired behavior.
The fix for this issue to avoid the `Uri.ToString()` method in storing the links and leverage either the `Uri.AbsoluteUri` property for absolute `Uri`s or the `Uri.OriginalString` property for relative …

Fix inconsistent URI encoding for Bundle links

---

src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
src/Hl7.Fhir.Core/Model/Bundle.cs

Reverts ewoutkramer/fhir-net-api#282
Needs to go in develop, not master.

Revert "Fix inconsistent URI encoding for Bundle links"

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Marten/nl-core-humanname-snapshot.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Marten/nl-core-patient-snapshot.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/CustomIdentifier.structuredefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/PatientExtension.structuredefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/PatientWithCustomIdentifier.structuredefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/PatientWithExplicitCoreIdentifierProfile.structuredefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/PatientWithExtension.structuredefinition.xml
src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
src/Hl7.Fhir.Specification/Specification/Navigation/ProfileReference.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/DifferentialTreeConstructor.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotBaseComponentGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorAnnotations.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorExtensions.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorOutcome.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorSettings.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotRecursionStack.cs

Properly merge external type profiles (incl. extension definitions).
Generate correct base element references.
Suppress invalid annotations on DomainResource.extension default properties (short, comments, definition).
Implement public overload for the ExpandElement method that accepts a (positioned) navigator.
Warning: this introduces some breaking changes in the public interface of the snapshot generator. Some public configuration settings have been renamed. Also some public members concerning extensions and annotations have been renamed.

Develop - Bugfixes for snapshot generator

---

src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/WMR/MySlicedOrganization.structuredefinition.xml
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

Related to issue reported by Marten Smits.
As discussed with Ewout, there is no (technical) reason for API not to accept this.
So I've simply removed the explicit check.
However, Vadim commented that this may introduce issues for code generators...

Snapshot Generator - accept slices on non-repeating, non-choice type elements

---

src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorOutcome.cs
src/Hl7.Fhir.Specification/Specification/Source/ResourceResolverExtensions.cs

Bugfix for an issue originally reported by NHS.
Symptom: if profile constrains binding.strength, then the snapshot should inherit .description and .valueSet[x] from the base profile. However actually the snapshot only contains the .strength constraint; the inherited properties are missing.
Intended behavior: The snapshot generator should recursively merge all unconstrained properties (not present in diff) from base profile.
=> Fixed method ElementDefnMerger.mergeComplexAttribute
=> Add unit test SnapshotGeneratorTest.TestElementBinding
[Edit] Added another commit to reject invalid element type profiles with incompatible target type.
Example 1: profile extension element mapped to a StructureDefinition that is not an extension definition.
Example 2: Patient.identifier element mapped to …

bugfix: snapshot generator - properly merge complex components (e.g. binding)

---

src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Ardon/zib-Procedure.structuredefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Ardon/zib-Procedure_Requester.structuredefinition.xml
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

The snapshot generator was hard coded to disallow child constraints on a choice type element.
The snapshot generator is now capable of expanding a choice type element provided that all the allowed element types share a common type code; the generator will then merge the children of the core type profile.
Specifically, this allows a profile to express a common extension constraint on a choice type element w/o type slicing. Such an extension constraint applies to all the accepted element types.

bugfix: snapshot generator - merge common constraints on choice type

---

src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Vadim/KulePrescribing.structuredefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Vadim/MedicationStatement-prescribing.structuredefinition.xml
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorOutcome.cs

- Fix merging of renamed choice type elements (e.g. base = value[x], diff = valueQuantity)
- prevent invalid warning about choice type constraints
In some circumstances, the Snapshot Generator would incorrectly consider certain type constraints on a choice type element to be invalid and emit an operation outcome issue. The generator now tries to process all the existing type constraints in diff without any validation. Caller is responsible for validating the actual constraints.
- never inherit name from root element (e.g. SimpleQuantity)

bugfix: SnapshotGenerator - fix choice type elements

---

src/Hl7.Fhir.Core/Rest/FhirClient.cs

STU3 is more clear that HTTP DELETE can return status code 200 - see http://hl7.org/fhir/http.html#delete
Deletes are currently failing for me on the HAPI 2.4 CLI test server with a FhirOperationException: 'Operation concluded successfully, but the return status 200 was unexpected'.

Fix for delete returning a status code of 200 being treated as unexpected

---

src/Hl7.Fhir.Core/Model/Base.cs
src/Hl7.Fhir.Core/Model/Code.cs
src/Hl7.Fhir.Core/Model/Element.cs
src/Hl7.Fhir.Core/Model/Extension.cs
src/Hl7.Fhir.Core/Model/FhirString.cs
src/Hl7.Fhir.Core/Model/Primitive.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorAnnotations.cs

I added the serializable attribute on some Fhir.Model classes that are required by the Orleans framework in order to send a StructureDefinition serialized to clients

Mark types as serializable to enable Orleans serialization of a StructureDefinition

---

src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
src/Hl7.Fhir.Core.Tests/TestData/issue-444-testdata.xml
src/Hl7.Fhir.Core/ElementModel/PocoElementNavigator.cs

The implementation of MoveNext() on the PocoNavigator was incorrect, generating incorrect Locations. This happened whenever two consecutive repeating properties were encountered, the index of the path indexer (Bla.blie[x].bla[y]...) was counting the number of times the same element name was encountered, but this was not reset when a new element was encountered.

fix: moveNext() would not reset index

---

src/Hl7.Fhir.Specification.Tests/Snapshot/InMemoryProfileResolver.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/TimingSource.cs
src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
src/Hl7.Fhir.Specification/Specification/Source/IConformanceSource.cs
src/Hl7.Fhir.Specification/Specification/Source/ZipSource.cs

No use casting return value to IReadOnlyList<T>, better to return the original concrete type.

Feature #497 - IConformanceSource.ListSummaries returns ReadOnlyCollection

---

src/Hl7.Fhir.Core/Serialization/ComplexTypeWriter.cs

Hi Ewout,
by adding this null check, the DispatchingWriter will throw an error in it's Serialize method:
"The FHIR serialization does not support arrays with empty (null) elements"

Fix null reference exception in ComplexTypeWriter.

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs

This fix is part of issue #536

fix: remove trailing slash in case of Transaction

---

src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
src/Hl7.Fhir.Core/Serialization/FhirSerializer.cs
src/Hl7.Fhir.Core/Serialization/JsonDomFhirWriter.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/InMemoryProfileResolver.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/TimingSource.cs
src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
src/Hl7.Fhir.Specification.Tests/Source/SummarySourceTests.cs
src/Hl7.Fhir.Specification.Tests/TimingSource.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
src/Hl7.Fhir.Specification/Specification/Source/IConformanceSource.cs
src/Hl7.Fhir.Specification/Specification/Source/ISummarySource.cs
src/Hl7.Fhir.Specification/Specification/Source/ZipSource.cs

* #543 Remove ListSummaries() from IConformanceSource
previous build introduced new method IConformanceSource.ListSummaries(), however this breaks binary compatibility => move this method to a separate new interface ISummarySource.
* #545 Support XML/JSON serialization to in-memory DOM
Implement public methods to serialize to Xml/Json document
(FhirXmlSerializer, FhirJsonSerializer)

ISummarySource & Serialize to DOM

---

src/Hl7.Fhir.Support.Tests/Utils/EnumMappingTest.cs
src/Hl7.Fhir.Support/Utility/EnumUtility.cs

Useful when parsing token search parameters, that must be case-insensitive
Also: moved the EnumUtility tests into Support.Tests - matching where the class is

Support: ignoreCase option for ParseLiteral

---

src/Hl7.FhirPath.Tests/HL7.FhirPath.Tests.csproj
src/Hl7.FhirPath.Tests/PocoTests/FhirPathParallelTest.cs

FhirPath evaluation gets mixed up when used heavily in parallel.
I have created a unittest to show this.
The unittest runs for about 3 min, because it loads all DataElement resources from specification.zip.
Unittest contains comments on what it does.
[FhirPath-Parallel-TestResults-BothFailing_201804226_1000.txt](https://github.com/ewoutkramer/fhir-net-api/files/1950281/FhirPath-Parallel-TestResults-BothFailing_201804226_1000.txt)

test: fhirpath-parallel

---

src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
src/Hl7.Fhir.Core/Rest/EntryToHttpExtensions.cs

Using the in-built FormUrlEncodedContent .NET framework class to encode according to specification.
Encode the body/content using the class System.Net.Http.FormUrlEncodedContent as as requested in PR #597

Fix: Encode according to FormUrlEncoded spec

---

src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
src/Hl7.Fhir.Core/Introspection/PropertyInfoExtensions.cs
src/Hl7.Fhir.Core/Introspection/PropertyMapping.cs

Hi @ewoutkramer, great optimization, we can also avoid the penalty of `Lambda.Compile()` by using a little bit of lightweight codegen. Given there is a known context around the models it seems relatively straight forward to do.
By calling Compile vs ILGen I was getting this type of perf to generate 100,000 getters:
```
00:00:00.8095830 (Generated using ILGen)
00:00:19.8382566 (Generated using Expression.compile)
```

Faster generation of property getters and setters with reflection emit

---

src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
src/Hl7.Fhir.Specification/Specification/Source/DirectorySourceSettings.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummary.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryExtensions.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryGenerator.cs

Implement #662 DirectorySource - optimize locking strategy
Benefits:
- Read access is now lock-free
- Reduce complexity, facilitate maintenance
Note: this change required a minor breaking change, as the ArtifactSummaryGenerator class is no longer static. However this is unlikely to affect many consumers, and compilation errors are trivial to fix.

fix: #662 - DirectorySource - optimize locking strategy

---

src/Hl7.Fhir.Core/Specification/PocoStructureDefinitionSummaryProvider.cs

Small optimization to improve performance of the FhirXmlSerializer class, especially when a debugger is attached.

rewrite: PocoElementSerializationInfo - Use LazyInitializer instead of Lazy<T>, to improve performance (esp. in debugger)

---

src/Hl7.Fhir.Core/FhirPath/FhirEvaluationContext.cs
src/Hl7.Fhir.Core/Support/CanonicalUrlConflictException.cs

Cleaning up the compiler warnings. The obsolete warnings (CS0618) still exists and will be removed in future release

fix: remove warnings (except obsolete warnings)

---

src/Hl7.Fhir.Core/Rest/FhirOperationException.cs

GetObjectData and [SecurityCritical] caused problems in low-rust environments without providing benefits. Removed GetObjectData. Whenever we'd wish to re-introduce this, dig up #738 and re-apply that code and pattern for all Exceptions we define in the library. This would also require platform-dependent conditional compile statements for high-security platforms.

Remove GetObjectData and [SecurityCritical] from FhirOperationException STU3

---

src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
src/Hl7.Fhir.Core/Serialization/FhirJsonParser.cs
src/Hl7.Fhir.Core/Serialization/FhirXmlParser.cs

Made dataType parameter optional in FhirXmlParser. Added Unit test for this change.

Add type-less overload for Parse method #726

---

src/Hl7.Fhir.Serialization/Hl7.Fhir.Serialization.csproj

The embedded resources (xsd files needed for xhtml validation) were also included as Content items, so they appeared in the NuGet. I have removed them from the output now.

fix: xml.xsd/fhir-xhtml.xsd accidentally got included in the NuGet

---

src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
src/Hl7.Fhir.Specification/Specification/Terminology/LocalTerminologyService.cs

fix: terminology service would throw when encountering an empty code

---

src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
src/Hl7.Fhir.Specification/Support/Issue.cs

Incorrect displays for codes resulted in an Error outcome in the local terminology service. This will now raise just a warning.
Fixes #624

feature: turn incorrect displays for codes into warnings

---

src/Hl7.Fhir.Core/Model/BackboneElement.cs
src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs

BackboneElement wasn't marked with [FhirType], so the ClassMapper wouldn't map it, therefore the PocoSDProvider wasn't able to retrieve type information for BackboneElement.
Fixes 793

fix: Added [FhirType] to BackboneElement to make sure it gets mapped. 

---

src/Hl7.Fhir.Support.Tests/CacheTests.cs
src/Hl7.Fhir.Support/Utility/Cache.cs
src/Hl7.FhirPath.Tests/Tests/FhirPathTest.cs
src/Hl7.FhirPath/FhirPath/IValueProviderFPExtensions.cs

Solves issue #561.
Time measurements:
_Before this improvement:_
- hitting the cache 20,000 times in 20 parallel tasks took an average time of 7,850ms (almost 8 sec).
This improvement:
- hitting the cache 20,000 times in 20 parallel tasks took an average time of 5,691ms.
- when we empty the cache by 10% of its size we get even a better performance. Then we have 4,725ms of time. This method is now implemented.

feature: new and faster cache for compiled FhirPaths

---

src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs

Improve unit test to cover both partial and full refresh

rewrite: update unit test for DirectorySource.Refresh()

---

src/Hl7.Fhir.Core/ElementModel/PocoBuilder.cs
src/Hl7.Fhir.Core/Serialization/ComplexTypeReader.cs
src/Hl7.Fhir.Core/Serialization/DispatchingReader.cs
src/Hl7.Fhir.Core/Serialization/PrimitiveValueReader.cs
src/Hl7.Fhir.Core/Serialization/ResourceReader.cs
src/Hl7.Fhir.ElementModel/TypedElementNode.cs
src/Hl7.Fhir.Serialization/FhirJsonNode.cs
src/Hl7.Fhir.Serialization/FhirXmlNode.cs

One of the causes of #821 was that it was unclear to the developer what the context of error messages was: are we parsing, serializing, type checking etc. Have now added that context on all components of the parse/type/serialize pipeline

#821: Improved error reporting by always mentioning the context of the error

---

src/Hl7.Fhir.Serialization/FhirXmlBuilder.cs
src/Hl7.Fhir.Serialization/FhirXmlSerializationSettings.cs

Made SkipUnknownElements obsolete in the FhirXmlBuilder. SkipUnknownElements now points to IgnoreUnknownElements.

Fixed IgnoreUnknownElements naming inconsistency.

---

LICENSE
src/fhir-net-api.props

Change the technical license structure in the solution to meet the nuget requirements. Also update the year in the copyright statement.

fix: change the technical license structure

---

src/Hl7.Fhir.Core/Model/ElementDefinitionExtensions.cs
src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Validation/TypeRefExtensions.cs
src/Hl7.Fhir.Specification/Validation/TypeRefValidationExtensions.cs

Validation of References to contained resources where there are multiple potential types, and the contained resource is not the first one targeted. 
Original in PR #829 of @brianpos

fix: Validation of References to contained resources where there are multiple potential types, See also PR #829

---

src/Hl7.Fhir.Core.Tests/FhirPathExtensionsTest.cs
src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
src/Hl7.Fhir.ElementModel.Tests/ScopedNodeTests.cs
src/Hl7.Fhir.Serialization.Tests/ParseDemoPatient.cs
src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonTyped.cs
src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonUntyped.cs
src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientXmlTyped.cs
src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientXmlUntyped.cs
src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientJson.cs
src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientXml.cs
src/Hl7.Fhir.Serialization.Tests/SerializePartialTree.cs
src/Hl7.Fhir.Serialization.Tests/StreamJsonResources.cs
src/Hl7.Fhir.Serialization.Tests/StreamXmlResources.cs
src/Hl7.Fhir.Serialization.Tests/SummaryTests.cs
src/Hl7.Fhir.Specification.Tests/JTokenExtensionsTests.cs
src/Hl7.Fhir.Specification.Tests/JsonNavigatorTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
src/Hl7.Fhir.Specification.Tests/Source/ResourceResolverTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/ProfileAssertionTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/SchemaCollectionTest.cs
src/Hl7.FhirPath.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
src/fhir-net-api.targets

This PR is probably in the nice to have section, it enables the tests to run on a Linux-based OS, as well as Windows. It should also work on Mac OS X, but I haven't tested it on OS X yet.
There are a few things here that I am not quite happy with.
1. In src/fhir-net-api.targets I have commented out the Otherwise section for VSTestLogger, since I was not able to get a proper listing of the tests in vscode. Not sure if this has any other implications like the build process or anything?
2. ~~In .gitattributes line endings are now `lf` for *.xml and *.json independently of platform, tried back and forth between `crlf` and `lf`, but `lf` was what ended up working on both Linux and Windows~~
3. Added a Thread.Sleep in ArtifactSourceTests::ZipCacherShouldCache at line 77.  Not sure what is going …

Enable cross-platform development

---

src/Hl7.Fhir.Support.Tests/PrimitiveTypeConverterTest.cs
src/Hl7.Fhir.Support/Serialization/PrimitiveTypeConverter.cs

Allow now also Exponents in de primitive type decimal, which actually only allowed from R4
So 1.2e2 is now also correct decimal.

Allow now also Exponents in de primitive type decimal

---

src/Hl7.Fhir.Core/Rest/WebRequestExtensions.cs

Uses first-class async primitives to handle timeouts in GetResponseAsync instead of a blocking .Wait call
This solves the case where `FhirClient` is used for large number of parallel calls (such as `TranslateConceptAsync`) and the `.Wait` call times out because active task slots are taken up by the waiting tasks.
The extra error handling for timeouts was not necessary, as the task returned by `Task.Factory.FromAsync` failed with an appropriate exception when it timed out.
Note that .NET Standard 1.1 still uses the old code because it doesn't have a timeout on the web request
removes several unused helper methods

better async for operations

---

src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs
src/Hl7.Fhir.ElementModel/Adapters/TypedElementToSourceNodeAdapter.cs
src/Hl7.Fhir.ElementModel/Properties/AssemblyInfo.cs

fix: TypedElementToSourceNodeAdapter returns now an ISourceNode annotation

---

src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummary.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryGenerator.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryHarvesters.cs

Implement ArtifactSummary.IsBundleEntry property, initialize value from INavigatorStream.IsBundle property.

fix: #904 ArtifactSummary should indicate Bundle entries

---

src/Hl7.Fhir.ElementModel/TypedElementNode.cs

fix: in the process of providing typeinfo to sourcenode a location is now also given in the errormessage

---

src/Hl7.Fhir.Serialization.Tests/SummaryTests.cs
src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs

All our tests were covering the parsing with PocoStructureDefinitionSummaryProvider. Added another test that uses StructureDefinitionSummaryProvider. This was also the case where Christiaan found the issue.

#896 Fixed the IsRequired check. Added unit test for it.

---

src/Hl7.Fhir.Core/Rest/FhirClient.cs

Updated the Transaction and TransactionAsync documentations in FhirClient. The functional behavior is correct.
#907

fix: 907 Transaction failure doesn't return null

---

src/Hl7.Fhir.Core/ElementModel/PocoBuilderExtensions.cs

Fixes #872, where we noticed we validate a bound Quantity accidentally against its "unit" +system not "code"+system.

fix: Quantity now binds to <code>, not <unit>

---

src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs

fix #875: DirectorySource.LoadArtifactByName should correctly match duplicate file names

---

src/Hl7.Fhir.Serialization/FhirXmlNode.cs

#889 Extra check added in order to skip the order validation for a node that was not part of the initial source tree read from a xml file.

fix: #889 Additional rules will get confused by hybrid typed trees

---

README.md
src/Hl7.Fhir.Serialization/FhirXmlNode.cs

This is the last forward merge from develop to develop-stu3. 
Because we will not develop anymore on DSTU2, the develop branch will be frozen. Only urgent hotfixes are allow on this branch (develop).

Changes from DSTU2 to STU3 (forward merge)

---

src/Hl7.Fhir.Specification/Support/Issue.cs

These were accidentally made readonly. Fixes issue #955.

fix: Remove readonly specifier from members of Issue

---

src/Hl7.FhirPath/FhirPath/Expressions/ExpressionNode.cs

To support the mapping language, we no longer require a function call invocation to depend on a focus (which was true for FhirPath expressions).

feature: allow FunctionCallExpressions without focus.

---

src/Hl7.Fhir.Core/Serialization/FhirJsonParser.cs
src/Hl7.Fhir.Core/Serialization/FhirXmlParser.cs

#941
Fixed the buildNodeSettings methods to use the parameter instead of the global variable.

Wrong usage of Setting parameter in buildNodeSettings

---

src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryGenerator.cs

New pull request based on develop-stu3, ready for porting to develop-r4.
Replaces the original pull request #954 for develop-r4 (broken, obsolete).

Fix: #952 - DirectorySource.Summaries - ignore unknown file extensions (2nd attempt)

---

src/Hl7.Fhir.Specification.Tests/xUnitBug.cs
src/Hl7.Fhir.Specification/Schema/Binding.cs
src/Hl7.Fhir.Specification/Support/Issue.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/SliceBucket.cs
src/Hl7.Fhir.Specification/Validation/Validator.cs

#992 Validation updates & minor bug fixes.
* Make the Issue.Create method public so that other systems may use this code to generate their own error messages using this infrastructure (including injecting their own Issues into the outcomes)
* The Constraint errors are on invariants, and so should use that issue type rather than just "invalid"
* Validation by Pattern also works - is same as by value with this implementation

Validation enhancements

---

src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
src/Hl7.Fhir.Core/Rest/SearchParams.cs

When using the '_sort' search result parameter to order the returned results there was a bug in the API in that it checked that values of the _sort must begin with a character that is either a letter or '-' for decreasing order. However, this rule neglected the case where the search parameter being used to sort was one of the 'Parameters for all resources' which all begin with an underscore character '_'. The prime example of this would be '[base]/Patient?_sort=_lastUpdated'
This commit adds support for underscore and a new test case.

_sort did not allow the use of underscore search parameter such as '_lastUpdated'

---

src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
src/Hl7.Fhir.ElementModel/ElementNode.cs
src/Hl7.Fhir.ElementModel/IShortPathGenerator.cs

Include an alternative implementation of CreateList that takes an IEnumerable list, rather than an array. This way you don't need to convert it to an array, which could be expensive in larger lists
Add a code comment for the shortpath generator that indicates what is different. (to help with coding)

ElementNode CreateList Overload and code comments

---

src/Hl7.Fhir.Core.Tests/Validation/ValidationTests.cs
src/Hl7.Fhir.Core/Model/DomainResource.cs

https://github.com/FirelyTeam/fhir-net-api/issues/1002
Changes:
* Remove the validation for the contained resource with Text
* Fixed a unit test which was validating the old behaviour
Note: There are 13 failing unit tests at this point. There were 13 failing prior to my change, so i have assumed these are not regression that ive cause by my edits.

#Fix for Issue 1002

---

src/Hl7.Fhir.Core/Rest/HttpToEntryExtensions.cs

#631 
Fixed: made the exception more clear for NETSTANDARD1_1

Explicit exception when converting header string to datetime 

---

src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
src/Hl7.Fhir.Core/Rest/FhirClientSearch.cs
src/Hl7.Fhir.Core/Rest/HttpToEntryExtensions.cs
src/Hl7.Fhir.Core/Rest/IFhirClient.cs
src/Hl7.Fhir.Serialization.Tests/RoundtripTest.cs

#971
Some [Obsolete] attributes removed as the plans to remove them have been postponed. Also cleaned up messages and warnings in the fhirclient code.

fix: inconsistent [Obsolete] attribute and some warning clean-up

---

src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
src/Hl7.Fhir.Core/Serialization/SerializerSettings.cs
src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientJson.cs
src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientXml.cs
src/Hl7.Fhir.Serialization/FhirJsonBuilderExtensions.cs
src/Hl7.Fhir.Serialization/FhirJsonSerializationSettings.cs
src/Hl7.Fhir.Serialization/FhirXmlBuilderExtensions.cs
src/Hl7.Fhir.Serialization/FhirXmlSerializationSettings.cs
src/Hl7.Fhir.Serialization/Utility/SerializationUtil.cs

#293 
Added new Setting for serializers to append new line at the end of json and xml outputs.

Empty line at the end of json and xml outputs

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs

#447
#791
As this constraint uses an unsupported FP syntax, we needed to disable it to avoid generating (unsolvable) validation errors.

Disable rng-2 fhirpath constraint

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs

#447
#791
As this constraint uses an unsupported FP syntax, we needed to disable it to avoid generating (unsolvable) validation errors.

Disable rng-2 fhirpath constraint (STU3)

---

src/Hl7.Fhir.ElementModel.Tests/SourceNodeTests.cs
src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/IssuesTests.cs
src/Hl7.Fhir.Support.Tests/EnumMappingTest.cs
src/Hl7.Fhir.Support.Tests/Hl7.Fhir.Support.Tests.csproj
src/Hl7.Fhir.Support.Tests/Utils/JsonAssert.cs

The unit tests for the support library had references on the POCO libraries, but it was easy to replace them so this dependency is no longer necessary.

feature: removed dependencies on POCO's in support unit tests

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/DifferentialTreeConstructor.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorAnnotations.cs

Fix for #1067 - Never expose/leak temporary internal annotations
Identical to fix for R4

fix: #1067 Incorrect root element base

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorManifestTests.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs

Fix for #1089
R4 SnapshotGenerator: Normalize element path of type slices in the snapshot.
i.e. rewrite `valueCode` to `value[x]:valueCode`.
Snapshot should never contain renamed elements.

fix: #1089 R4 SnapGen normalize type slice element path in snapshot

---

src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
src/Hl7.Fhir.Specification.Tests/TestData/validation/observation-profile-for-discriminator-test.xml
src/Hl7.Fhir.Specification.Tests/TestData/validation/string-extension-for-discriminator-test.xml
src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs

Will now handle extension() discriminators where the profile calling an extension has local (inline) constraints on the extension, and you want to discriminate on those, rather than the ones in the referenced extension.

fix: handle extension() discriminators with local constraints [stu3]

---

src/Hl7.Fhir.Core/Rest/WebRequestExtensions.cs

* Call WebRequest.Abort on timeout
* Fixes issue #1093

fix: Call WebRequest.Abort on timeout

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs

#1134 Added a unit test proving that all FHIRDateTime has its own pattern and is not necessary dependent on PartialDate class validation.

1134 Add validation to not allow timezones on time and date

---

src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
src/Hl7.Fhir.Core/Serialization/SerializerSettings.cs

https://github.com/FirelyTeam/fhir-net-api/issues/1176

Fix: now trims whitespaces of value attributes when serializing to xml

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/EntryToHttpExtensions.cs

* Using IEnumerable<KeyValuePair<string, string>> instead of Dictionary
in EntryToHttpExtensions.setBodyAndContentType
* Fixes #1206

fix: Multiple includes throws exception

---

src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs

reducing dataelements.xml to normal size. In the near future this xml file will not be included anymore in the distribution

fix: correct the dataelements.xml to normal size again

---

src/Hl7.Fhir.Core/Model/Element.cs
src/Hl7.Fhir.Specification.Tests/PocoSerializationInfoTests.cs

#1233 
element.id changes in R5

fix: change  TypeRedirect on element id from "Id" to "FhirString" and re-enabled unit test

---

src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs

TypedElementToSourceNodeAdapter should return IResourceTypeSupplier directly and not the underlying SourceNode

Adjust TypedElementToSourceNodeAdapterTests

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorExtensions.cs

checks if baseDefinition is annotated with the "interface" extension.  If so, skip and resolve the next baseDefinition.

fix: skip interfaces in getting baseDefinitions in snapshot generation

---

README.md

https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Unable.20to.20build.20.2ENET.20.20FHIR.20API.20solution/near/189593713 shows confusion about how to clone this repo correctly. The docs exist but aren't readily discoverable; the README should include links + details directly.

Embed link to and details about submodule cloning

---

src/Hl7.Fhir.Specification.Tests/SerializationInfoTestsHelpers.cs
src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs

I developed a comprehensive set of tests to check behaviour of the different `IStructureDefinitionSummaryProviders` for the various exceptional elements (like Element.id, Narrative.div etc).
This test is now present and exactly the same in R3+R4+R5.

#984 - Added tests for additional exceptional elements (for R3)

---

src/Hl7.Fhir.Specification.Tests/SerializationInfoTestsHelpers.cs
src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs

I developed a comprehensive set of tests to check behaviour of the different `IStructureDefinitionSummaryProviders` for the various exceptional elements (like Element.id, Narrative.div etc).
This test is now present and exactly the same in R3+R4+R5.

#984 - Added tests for additional exceptional elements (for R4) 

---

src/Hl7.Fhir.Specification.Tests/SerializationInfoTestsHelpers.cs
src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs

I developed a comprehensive set of tests to check behaviour of the different `IStructureDefinitionSummaryProviders` for the various exceptional elements (like Element.id, Narrative.div etc).
This test is now present and exactly the same in R3+R4+R5.

#984 - Added tests for additional exceptional elements (for R5)

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

In this PR the inheritance of a StructureDefinition's root element extensions is removed. This fix has to be ported to R5 and STU3 as well, although in the latter the inheritance does not lead to problems

#1325 - Removed root element extension inheritance in profiles

---

src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonUntyped.cs

Fixes #1304. 
Also raise an exception when the ResourceType is empty. Not only when the ResourceType is completely missing.

fix: 1304 - also raise an exception if the ResourceType is empty

---

src/Hl7.Fhir.Serialization.Tests/Hl7.Fhir.Serialization.Tests.csproj
src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientXmlTyped.cs
src/Hl7.Fhir.Serialization.Tests/TestData/no-namespace.xml

Parser: ignores xml namespace check on contained resources when permissive parsing is turned on

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs

When merging ElementDefs, the Max (cardinality) should never be merged in such a way that it is higher than the lowest of the base and diff.

#1303 - don't allow max to go from lower to higher

---

src/Hl7.Fhir.Core.Tests/Model/NullExtensionsTest.cs

Primitive<T> was an empty abstract type and did not have a function anymore.

rewrite: remove useless Primitive<T>

---

src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotBaseComponentGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Source/ResourceResolverExtensions.cs
src/Hl7.Fhir.Specification/Specification/Source/SnapshotSource.cs
src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpander.cs

* Add ConfigureAwait(false) where applicable
* Fix the SDSummaryProvider.Provide() call to just block instead of using Task.Run() -> fixes performance problems for now (until we have replaced the SDSummaryProvider with natively async stuff)

Add configure await & temp fix provider (for R3)

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

Fixes #618
Ignores invalid slicename error on SImpleQuantity root.

fix: snapshot generator: ignore invalid sliceName error on SimpleQuantity root

---

src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
src/Hl7.Fhir.Core/Rest/FhirClient.cs
src/Hl7.Fhir.Core/Rest/Legacy/LegacyFhirClient.cs

fixes #1132
Removed LastResponse and LastRequest from the FhirClient(s). They were already disposed, so no point having them around.

fix: removed LastReponse and LastRequest from FhirClient and LegacyFhirClient

---

src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpander.cs
src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpanderSettings.cs

fixes: #1418
Adds includeDesignations optionality in VS expander

feature: add includeDesignations parameter in ValueSet expander

---

src/Hl7.Fhir.Core/FhirPath/FhirEvaluationContext.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs

The differences between %context, %resource and %rootResource were not clear - added comments to the properties representing them, even renamed some. Then made sure validator passed in the right values to these FhirPath variables.

fix: #884 %resource confusion (for R3)

---

src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
src/Hl7.Fhir.Core/Model/ModelInfo.cs

IsInstanceTypeFor() was far to flexible, allowing e.g. `markdown` as an instance for `string`.  Although `markdown` is a variant of `string`, substitution is not allowed for these types. This PR corrects this mistake.

Correct IsInstanceTypeFor() in ModelInfo (R3)

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorExtensions.cs

We use now the `extension structuredefinition-interface` to identify the pattern/interface classes `CanonicalResource` and `MetadataResource`

Refactor R5: use of extension structuredefinition-interface

---

src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
src/Hl7.Fhir.Specification/Specification/Navigation/DiscriminatorInterpreter.cs

Fixes #1473 
Adding the function `as(type)` to the fhirpath simple, which is used in `ElementDefinition.slicing.discriminator.path`

Function as(type) to the fhirpath simple collection

---

build/ChangeTargetFramework.ps1

Finds all non-test project files and changes the target framework to a given framework (or frameworks).
This allows individual team members to speed up their build/debug cycle while working in a new feature, by disabling support for all frameworks. The CI build will of course check and build against all supported frameworks.

feature: Add script to quickly set TargetFramework on all csproj files

---

src/Hl7.Fhir.Core/Model/Generated/ImplementationGuide.cs
src/Hl7.Fhir.Core/Model/Generated/StructureMap.cs
src/Hl7.Fhir.Core/Model/Generated/Template-Bindings.cs
src/Hl7.Fhir.Core/Model/Generated/Timing.cs

Rollback the way of enum generating. This PR belongs to commit-id a678f25f9e2b25f00742b85da0b6ca3d0198c33d of microsoft/fhir-codegen

fix: back to old enum style for R5

---

src/Hl7.Fhir.Core/Model/Generated/StructureMap.cs

Rollback the way of enum generating. This PR belongs to commit-id a678f25f9e2b25f00742b85da0b6ca3d0198c33d of microsoft/fhir-codegen

fix: back to old enum style for STU3

---

src/Hl7.Fhir.Core/Model/Generated/ImplementationGuide.cs
src/Hl7.Fhir.Core/Model/Generated/StructureMap.cs
src/Hl7.Fhir.Core/Model/Generated/Template-Bindings.cs
src/Hl7.Fhir.Core/Model/Generated/Timing.cs

Rollback the way of enum generating. This PR belongs to commit-id a678f25f9e2b25f00742b85da0b6ca3d0198c33d of microsoft/fhir-codegen

fix: back to old enum style for R4

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs

STU3: fix: ElementDefinition.binding now gets merged on a level deeper in the snapshatgenerator

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs

R4: fix: ElementDefinition.binding now gets merged on a level deeper in the snapshotgenerator

---

src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs

fix: throws error on _sort search param value that consists of just a single dash

---

src/Hl7.Fhir.Core/FhirPath/ElementNavFhirExtensions.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathExtensionsTest.cs

It was throwing this exception:
```
System.InvalidCastException: Unable to cast object of type 'Hl7.Fhir.ElementModel.Types.Date' to type 'Hl7.Fhir.Model.Base'.
at Hl7.Fhir.FhirPath.ElementNavFhirExtensions.<>c.<ToFhirValues>b__6_0(ITypedElement r) in ...\firely-net-sdk\src\Hl7.Fhir.Core\FhirPath\ElementNavFhirExtensions.cs:line 117
at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
at System.Linq.Enumerable.SelectArrayIterator`2.TryGetFirst(Boolean& found)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
```
Unit test provided.

Fix issue with FhirPath "as date" expression .

---

src/Hl7.Fhir.Core/FhirPath/ElementNavFhirExtensions.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathExtensionsTest.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs

Fixes #1580. 
This R4 variant also includes unittests

R4: FhirPath 'as time' fails in a Select 

---

src/Hl7.Fhir.Core/FhirPath/ElementNavFhirExtensions.cs

Fixes #1580 . 
To complete the whole casting, we should also add the type 'time', not only 'date'. 
The unittest for this will be in the PR for R4

STU3: FhirPath 'as time' fails in a Select

---

src/Hl7.Fhir.Core.Tests/Model/TerminologyTests.cs

A recent PR in common (https://github.com/FirelyTeam/firely-net-common/pull/96) has added functionality to convert POCO codings to System codings. This adds a few tests to verify the functionality.

Updated to latest common to test new code conversion functions.

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/Validator.cs

fixes #1563 
Uses a better regex for string validation: `[\r\n\t\u0020-\uFFFF]*`

R4: Use a better validation regex for strings

---

README.md

Document breaking changes more clearly - it's somewhat hidden in the wiki at the moment, and not in the README as one would expect.

Updated Readme.md to document breaking changes more clearly

---

src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs

Created a static for ontoserver and placed all referring unit tests in the category IntegrationTest (= not run by Devops)
None

Terminology unit tests are not run in Devops anymore 

---

src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
src/Hl7.Fhir.Specification.Tests/StructureDefinitionWalkerTests.cs
src/Hl7.Fhir.Specification.Tests/TestData/validation/observation-profile-for-discriminator-test.xml
src/Hl7.Fhir.Specification.Tests/TestData/validation/patient-sliced-complex-extension.xml
src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs

Fixed a bug where a discriminator walking into a complex extension would not find the complex child extension.
Created a (valid) example of a profile that constrains a complex extension inline and fixed the walker to look for fixUri instead of a targetProfile.profile.
Fixes #1656.

Can now use a discriminator to walk into a complex extension (for R3)

---

src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
src/Hl7.Fhir.Specification/Validation/Slicing/DiscriminatorBucket.cs
src/Hl7.Fhir.Specification/Validation/Slicing/ExistsDiscriminator.cs

Adds support for `exists` slicing + added a unit test to verify.
Fixes #1578.

Add support for exists slicing

---

src/Hl7.Fhir.ElementModel.Tests/ScopedNodeTests.cs

In class `ScopedNode` the property `AtResource` can now also be determined from IResourceTypeSupplier when there is no `Definition` present.

ScopedNode: AtResource can also be determined from IResourceTypeSupplier

---

src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
src/Hl7.Fhir.Core/Serialization/BaseFhirSerializer.cs
src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs

Adding an extra setting `IncludeMandatoryToElements` to `SerializeSetting` . This is used during serialization with a set of elements:
```c#
var json = new FhirJsonSerializer(new SerializerSettings() { IncludeMandatoryToElements = true })
.SerializeToDocument(obs, elements: new[] { "issued" });
```
In above case, not only the element `issued` is serialized but also the mandatory elements. For `Observation` is that `status`. So 2 elements are serialized here. 
Resolves #1653.
Unit test `SerializationTests.IncludeMandatoryToElementsTest`

Optional include of mandatory elements to the list of provided elements during serialization

---

src/Hl7.Fhir.Specification/Validation/ElementDefinitionNavigatorExtensions.cs

Made some extensions on `ElementDefinitionNavigator` public since there is potential for re-use

Made some extensions of ElementDefinitionNavigator public (for R3)

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/TypedEntryResponseToBundle.cs

FhirClient: handle prefer operation outcome in resource response

---

src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs

Points to new common commit where FhirPath input is wrapped in ScopedNode before evaluating
Fixes #1525 
Added unit test in FhirPathTests.cs

[R4] Always wrap FhirPath input in scopednode before evaluating 

---

src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathOperationTests.cs

Unit Tests for the fix for the 'as' operator committed in FhirPath
library in the firely-net-common repository
(note: this is a cherry-picked version of PR #1721, but moved unto the R4 branch, where we keep all our poco-based FhirPath tests)

Tests: FhirPath 'as' can return FHIR primtives (for R4)

---

src/Hl7.Fhir.Core/Model/Generated/Citation.cs
src/Hl7.Fhir.Core/Model/Generated/Statistic.cs

The codegenerator is handling the naming for nested backbone elements in a different way for the resources `Citation` and `Statistics`.

Re-ran the codegen for 4B (Statistics and Citation)

---

src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
src/Hl7.Fhir.Core/ElementModel/PocoBuilderExtensions.cs
src/Hl7.Fhir.Core/ElementModel/TypedElementExtensions.cs
src/Hl7.Fhir.Core/Model/ModelInfo.cs
src/Hl7.Fhir.Core/Properties/AssemblyInfo.cs
src/Hl7.Fhir.Core/Specification/PocoStructureDefinitionSummaryProvider.cs

Adds functionality to convert common POCOs to/from ITypedElement without the need of FHIR-version specific assemblies

Support serialization of types in Common

---

src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs

Keep existing timezone by default in FhirDateTime.ToDateTimeOffset - STU3

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/Validator.cs

Catch expected exceptions for slice setup and typechecking (while parsing) to make sure they don't bubble up to create an "internal logic error".
Fixes #1668

1668 Avoid excessive "internal logic exception" messages.

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs

There was incorrect FhirPath expression for `con-3`. This should be fixed by the standard, but in the meantime we fix this in our definition files.
In addition, we encountered another error in the `CopyTo` function of `ValidationSettings`: the member `ConstraintBestPractices` was missing during copying.
Fixes #1283 
Tested by `BasicValidationTests.ConditionCon3ConstraintTest`

R4: 1283 - Repair of constraint con-3 of Condition

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Specification/Source/SchemaCollection.cs
src/Hl7.Fhir.Specification/Specification/Source/ZipSource.cs
src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs
src/Hl7.Fhir.Specification/Validation/XmlValidationExtensions.cs

When using the XML validation features of the validator, the user should be able to configure where to get the necessary XSD schemas from.

Make the location for XSD schemas configurable

---

build/azure-pipelines.yml

In the previous release the determination of the current and previous tags went wrong. Now these tags are determined in the build stage.

Devops: Create Release Notes automatically

---

src/firely-net-sdk.props

Suppress warning CS1591 (Missing XML comments) in Release mode. It flooded the warnings in Azure Devops, in such a way that we do not see important warnings anymore.

Suppress warning CS1591 (Missing XML comments) in Release mode

---

LICENSE

Adds the license type, this allows Github to give more contextual licensing information, e.g.
Closes|Fixes|Resolves [issue #].
Documentation update

Adds license type

---

src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs

FHIR Specific variables `%rootResource` and `%resource` are now set correctly. See also the assumptions in https://github.com/FirelyTeam/firely-net-sdk/issues/1742#issuecomment-875598124.
See also PR FirelyTeam/firely-net-common#135
Resolves #1742 
`TestFhirPathRootResource()` in FhirPathTest.cs

R4: FHIR Specific variables %rootResource and %resource are set correctly now

---

src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs

See PR: #1802 and FirelyTeam/firely-net-common#135
Resolves #1742

STU3: FHIR Specific variables %rootResource and %resource are set correctly now

---

build/azure-pipelines.yml
build/templates/sign-dlls-template.yml
src/firely-net-sdk.props

We delay the signing of the dll's in order to allow external pull requests. The signing is done now just before packaging the dll's.
See also PR: https://github.com/FirelyTeam/firely-net-common/pull/142

Devops: delay signing of dll's

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

When you were using a profile with an element that has again a profiled type. then the snapshot generator used the cardinality of that profiled type, and not the cardinality of the element. So
For example when you profile the element `Observation.code` and you use a derived type for this element, for example `CodeableConceptProfile`, then the cardinality of `CodeableConceptProfile` was used for the element  `Observation.code`. In this case the minimum cardinality of `Observation.code` went from `1`  to `0`, which is incorrect. This has been solved in this PR.
Fixes #1824 
Unit test `SnapshotGeneratorTest2.CheckCardinalityOfProfiledType()`

Snapshot generator: corrected cardinality of element with a derived type

---

src/Hl7.Fhir.Specification.Tests/TestData/validation/profile-communication.xml
src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
src/Hl7.Fhir.Specification/Validation/Slicing/BucketFactory.cs
src/Hl7.Fhir.Specification/Validation/Slicing/ComprehensiveDiscriminator.cs
src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs

Using combined discriminators will now also work when one of the discriminators does not discriminate. 
Also solved in this PR:
- `resolve()` in a discriminator expression will also work when it is executed on the Reference definition (the targetProfiles are copied into the SDWalker
Fixes #1686.
Describe how this change was tested.

STU3: Combined discriminators can now also be used when one of them cannot discriminate

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

Use Element as primary data type for polymorphic elements [STU3]

---

src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
src/Hl7.Fhir.Core.Tests/TestData/test-similar-valuex.json

fixes https://github.com/FirelyTeam/firely-net-sdk/issues/1858

Return correct match when parsing similar polymorphic elements in a single resource [R5]

---

src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.csproj

[Recommended](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target) by Microsoft to add `netstandard2.0` as a TargetFramework as well. Also when you already target `netstandard1.x`

Added netstandard2.0 as one of the TargetFrameworks

---

src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.csproj

Upgrade one of the TargetFrameworks from .NET 4.5 (`net45`) to .NET 4.5.2 (`net452`).
.NET 4.5 is not supported anymore by Microsoft

Changed TargetFramework from net45 to net452

---

build/azure-pipelines.yml

Move task(s) for publishing packages on GitHub in a separate pipeline stage

Devops: Move task(s) for publishing packages on GitHub in a separate pipeline stage

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/TypeRefValidationExtensions.cs

A profile that had a target profile on a reference type *and* other child definitions on that reference, then the validator did not resolve the reference and skipped the whole validation of that referenced resource. This has been resolved now. 
Fixes #1654 
See `BasicValidationTests.ValidateWithTargetProfileAndChildDefinitions`

Validate resources with targetprofiles and child definitions

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs

The Validator now also checks the cardinality of extensions used in an instance. The cardinality is defined in the root of the extension.
Fixes #1790 
Unit test `Hl7.Fhir.Specification.Tests.BasicValidationTests.ValidateExtensionCardinality`

Validator: also validate the cardinality of extensions in an instance  

---

build/azure-pipelines.yml

Removal of stage MyGet: Firely .NET packages are published only to GitHub now. Also publishing of those packages to GitHub are done by a general template.

Devops: publish the packages to GitHub via templates

---

src/Hl7.Fhir.Core.Tests/Rest/ContentTypeTests.cs
src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
src/Hl7.Fhir.Core/Rest/BundleToEntryRequest.cs

Removes MIME-type `fhirVersion` from Accept header. Use the `FhirClientSettings.UseFhirVersionInAcceptHeader` to add the `fhirVersion` back into the Accept header. The default behavior is that this MIME-type parameter is not added to the Accept header. Hence the breaking change.
See also PR https://github.com/FirelyTeam/firely-net-common/pull/165 
Fixes #1899.
Unit test `Hl7.Fhir.Core.Tests.Rest.FhirClientMockTest.AcceptHeaderTest`

FhirClient: remove MIME-type fhirVersion from Accept header

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

Continue merging diff child constraints in the case of multiple types.
Resolves #1898.
See unit test `Hl7.Fhir.Specification.Tests.SnapshotGeneratorTest2.ContinueMergingChildConstraintsMultipleTypes`

SnapshotGenerator: continue merging diff child constraints with multiple types

---

src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs

This is just a new common with the latest version of FP with new FhirPath date comparison logic
+ slight adaption of the unit tests to reflect these changes.

Add FhirPath math for date(Time)/duration additions (for R4)

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs

Remove the ignore option in the validation setting to check best practices constraints

---

src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/Issue-1981-Patient.StructureDefinition.xml
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

In PR #1826 we introduced a bug in existing functionality. We resolved that now by a 3-way merge of the cardinality of
- snapshot
- differential
- external profile type
The most constrained value will win. Let's say we have the following cardinalities on an element:
- snapshot: `0..*`
- differential: `1..*`
- external profile type (like an extension): `1..1`
Then the result cardinality of the element would be: `1..1`
This behavior is also applied to the "normal" merge of `Min`: in the past the Min value of the differential was copied to the snapshot (when it exists). Now  both Min values (snap and diff) are compared first, and the highest value wins.
Resolves #1981.
- `SnapshotGeneratorTest2.TestMinMax`
- `SnapshotGeneratorTest2.CardinalityOfExtension`

3-way merge of cardinality of an element

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core.Tests/Rest/OperationsTests.cs
src/Hl7.Fhir.Core.Tests/Rest/ReadAsyncTests.cs
src/Hl7.Fhir.Core.Tests/Rest/RequesterTests.cs
src/Hl7.Fhir.Core.Tests/Rest/SearchAsyncTests.cs
src/Hl7.Fhir.Core.Tests/Rest/UpdateRefreshDeleteAsyncTests.cs
src/Hl7.Fhir.Core/Rest/Legacy/LegacyFhirClient.cs
src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

- Make the class `LegacyFhirClient` obsolete, This will be removed in the next major release
- Solving some compiler messages

Make LegacyFhirClient obsolete

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/Issue-1981-Patient.StructureDefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/TestExtension01.StructureDefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/TestExtension0star.StructureDefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/TestExtension11.StructureDefinition.xml
src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/TestExtension1star.StructureDefinition.xml
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

PR #1990 did not solve the issue (checked with additional unit tests). That is because the use of the new mergeMin and MergeMax methods in ElementDefnMerger is enough to fix both #1824 and #1981. The additonal code in mergeTypeProfiles to set the Min/Max of the rebasedRootElem is no longer valid.
Resolves #1981 and #1824.
Additional unit tests were added for CardinalityOfExtension.

Fix for PR #1990

---

build/azure-pipelines.yml
build/build-variables.yml

The produced nuget packages are now signed by a code signing certificate of Firely.
The public key is installed at NuGet for the organization Firely, and the private key is stored at a Azure Key Vault, together with the password for this key. To access those secrets in the Azure Key Vault a Variable Group `CodeSigning` has been created in the Devops project `firely-net-sdk`.
The signing itself is done by a Firely template, which can be found [here](https://github.com/FirelyTeam/azure-pipeline-templates/blob/master/codesign-nuget-packages.yml).
Also the flag `/p:ContinuousIntegrationBuild=true` has been added to the build to make the compilation deterministic.
Resolves issue #2041

Signing the NuGet Packages

---

src/firely-net-sdk.props

To enhance our code, we added the compiler option `TreatWarningsAsErrors`
Resolves issue #2034.
See also PR FirelyTeam/firely-net-common/pull/192

Treat warnings as errors

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/FhirClient.cs

When creating the new HttpClient inside the constructor indicate that if it is a shared MessageHandler and therefore that it should not be disposing it when it is finished with it.
As the change in the common lib has a default parameter this is not a truly breaking change, and in the R4 (version level) functionality the public surface has not changed this is not tagged as a breaking change.
Resolves [issue #2029].
The unit test `CallsCallbacksHttpClient` was used to verify this functionality, as it fails when the fix is not applied.

Do not dispose of a shared HttpMessageHandler passed into the constructor

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs

The unit test TestExpandBundleEntryResource did not test the snapshot generator outcome because the snapshot elements were fully expanded after the act and used for comparison.
Not applicable.
Added additional test cases.

Updated unit test TestExpandBundleEntryResource.

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/FhirClient.cs

When creating the new `HttpClient` inside the constructor indicate that if it is a shared MessageHandler and therefore that it should not be disposing it when it is finished with it.
As the change in the common lib has a default parameter this is not a truly breaking change, and in the R4 (version level) functionality the public surface has not changed this is not tagged as a breaking change.
Resolves #2029
The unit test `CallsCallbacksHttpClient` was used to verify this functionality, as it fails when the fix is not applied.

STU3: Do not dispose of a shared HttpMessageHandler passed into the constructor

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/FhirClient.cs

Support providing the HttpClient direct to the FhirClient instead of the HttpClientHandler (as another alternative)
This then supports creating unit tests as described here for webapi based projects
https://www.hanselman.com/blog/minimal-apis-in-net-6-but-where-are-the-unit-tests
Resolves/Contributes to #2046 #2036 (may be able to now push the HttpClientFactory work to the callers, and not be required in the FirelySDK at all)
Additional unit test included (and also included in my server to verify that can unit test as shown)

Support providing the HttpClient direct to the FhirClient

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
src/Hl7.Fhir.Core/Rest/FhirClient.cs

Support providing the `HttpClient` direct to the `FhirClient` instead of the `HttpClientHandler` (as another alternative)
This then supports creating unit tests as described here for webapi based projects
https://www.hanselman.com/blog/minimal-apis-in-net-6-but-where-are-the-unit-tests
Resolves/Contributes to #2046 #2036 (may be able to now push the `HttpClientFactory` work to the callers, and not be required in the FirelySDK at all)
Additional unit test included (and also included in my server to verify that can unit test as shown)
@brianpos

Support providing the HttpClient direct to the FhirClient - STU3

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs

The unit test TestExpandBundleEntryResource did not test the snapshot generator outcome because the snapshot elements were fully expanded after the act and used for comparison. Cherry picked commit from develop-stu3 and corrected for R4.
Not applicable.
Added additional test cases.

Updated unit test TestExpandBundleEntryResource for R4

---

src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Schema/Binding.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/TypeRefValidationExtensions.cs

`IssueComponent.Location` is deprecated. We use now  `IssueComponent.Expression`
Resolves #1692.
Existing tests
PR FirelyTeam/firely-net-common/pull/196

Use IssueComponent.Expression instead of IssueComponent.Location

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs

Catch InvalidOperationException when FhirClient encounters non-FHIR Json/XML in the response - STU3

---

build/azure-pipelines.yml

Signing of the NuGet Packages is not done anymore for Pull Requests. Because externals that are creating PRs cannot access our secrets, like code certificates or signing passwords, which is a good thing ;)

Signing of NuGet packages is not done anymore at PR builds

---

build/azure-pipelines.yml

The pattern for uploading NuGet packages has been broadened, so that symbol packages are also uploaded.
Resolves #2094 
Check after a release if the symbols packages are uploaded as well.

Symbol packages are also uploaded to NuGet

---

src/Hl7.Fhir.Specification.Tests/Snapshot/ElementDefinitionPropertyProxy.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs

Extensions on Binding and Constraint are not merged from the differential to the snapshot.
Fixes #2091.
Unit test ElementDefinitionPropertyExtensionTest.
I have backported some code from R4 to fix the problem for Constraint extensions.

Extensions on Binding and Constraint are not merged from the differential to the snapshot (STU3)

---

src/Hl7.Fhir.Specification.Tests/Snapshot/ElementDefinitionPropertyProxy.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs

Extensions on Binding are not merged from the differential to the snapshot.
Fixes #2091 
Unit test ElementDefinitionPropertyExtensionTest.

Extensions on Binding are not merged from the differential to the snapshot (R4)

---

src/Hl7.Fhir.Specification.Tests/Source/FhirPackageSourceTests.cs
src/Hl7.Fhir.Specification/Specification/Source/FhirPackageSource.cs

Added factory method for creating a FHIR Core Package source [R5]

---

src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
src/Hl7.Fhir.Core.Tests/TestDataHelper.cs
src/Hl7.Fhir.Core.Tests/Validation/SearchDataExtraction.cs
src/Hl7.Fhir.Core.Tests/Validation/ValidationTests.cs
src/Hl7.Fhir.Core/Rest/FhirClientSearch.cs
src/Hl7.Fhir.Serialization.Tests/RoundtripTest.cs
src/Hl7.Fhir.Serialization.Tests/StreamXmlResources.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryExtensions.cs
src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryPropertyBag.cs
src/Hl7.Fhir.Specification/Specification/Source/ZipCacher.cs
src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs

There were a lot of unused `#if NET40` still in the code. Those compiler directives were for .NET Framework 4.0, but we don't target that framework anymore. 
By doing this we also removed the reference to `SharpZipLib`

Remove unused #if NET40

---

src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs

When the `FhirClientSettings.VerifyFhirVersion` = `false` (which is the default), the `FhirClient` is now able to connect to another FHIR server with another FHIR version. It is now possible that a R4 FhirClient can connect to a R4B server. When there are errors, we provide additional information that the client and server may not be compatible.
Resolves #2131 
See the `FhirClientMockTest`

Allow the FhirClient to connect to other FhirVersions servers

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/firely-net-sdk-tests.props

Remove binding from the snapshot after Type slicing and the slice does not contain a bindable type.
Resolves #2132 .
See unit test BindingRemovedAfterTypeSlicing()

STU3: Remove binding after Type slicing and the slice does not contain a bindable type

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/firely-net-sdk-tests.props

Remove binding from the snapshot after Type slicing and the slice does not contain a bindable type.
Resolves #2132 .
See unit test BindingRemovedAfterTypeSlicing()

R4: Remove binding after Type slicing and the slice does not contain a bindable type

---

src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs

The following invariants are corrected during validation:
- `eld-19`: changed the expression in `matches()` so that the *whole* string is matched 
- `eld-20`: changed the expression in `matches()` so that the *whole* string is matched
- `sdf-0`: changed the expression in `matches()` so that the *whole* string is matched
- `sdf-24`: do not use `$this` in the expression, see also https://jira.hl7.org/browse/FHIR-37761
- `sdf-25`: do not use `$this` in the expression, see also https://jira.hl7.org/browse/FHIR-37761
- `ref-1`: Reference with only a display should succeed. See https://jira.hl7.org/browse/FHIR-37793
- `que-7`: use the correct FHIR boolean, see also https://jira.hl7.org/browse/FHIR-25390
Resolves #2013 
Resolves #2153 
Resolves #2174 
Unfortunately no unit tests, because I could …

Repair some invariants during validation

---

src/Hl7.Fhir.Specification.Tests/Source/ZipSourceTests.cs

fixes [#2031](https://github.com/FirelyTeam/firely-net-sdk/issues/2031)
I have doubts about the location of the unit test, any suggestions?

Corrected fullUrl for valueset-compose-include-valueSetTitle

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs

fixes: 2118
Needed to backport some logic from R4 and add an nullable argument to a public function to fix this in STU3

[SnapshotGenerator] Fix invalid constraint sources [STU3]

---

src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs

Improvement of the following invariants:
- ref-1
- sdf-24 
- sdf-25
And add an unit test to prove it.
Resolves #2153 
See `BasicValidationTests.InvariantValidation`

Improvement of invariants ref-1, sdf-24 and sdf-25 [R4]

---

src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotElementMatcherTests.cs
src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
src/firely-net-sdk-tests.props

Will now create a type slice for type slices introduced with just a sliceName.  Such slices will now also explicitly set type slices to open (R4 semantics).
Fixes #2232.

2232 Support implicit type slicing

---

src/Hl7.Fhir.Specification.Tests/Validation/IssuesTests.cs
src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/TypeRefValidationExtensions.cs
src/Hl7.Fhir.Specification/Validation/Validator.cs

[Validator] Also validate the instance type when the definition has children

---

src/Hl7.Fhir.Core.Tests/Rest/OperationsTests.cs
src/Hl7.Fhir.Core/Rest/FhirClientTermSvcExtensions.cs
src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs

Merged backwards PR #2225 
Update the parameter to be conformant with the R4+ specification
Update the URL of the CSIRO test server to use the R4 server, not STU3 endpoint.
_(Not sure if you'd mark this as a breaking change, but it's now conformant with the R4 spec, would have been working with many terminology servers as they've been tolerant of the old parameter name)_
Resolves #2106
Unit test InvokeExpandExistingValueSet updated to also cover this code path.

2106 - Terminologyserviceexpand

---

src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
src/Hl7.Fhir.Core/Serialization/BaseFhirParser.cs

In order to be able to inject custom error/exception handling to the parser need to be able to provide the handler through the settings object on the parser.
Resolves #2222
The unit test `ConfigureFailOnUnknownMember` was updated to verify this new functionality

Pass the exceptionhandler in from the settings into the pocobuilder

---

src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
src/Hl7.Fhir.Specification/Schema/Binding.cs

The exception message should be added to the response message.
Part of #2224
Unit test `ErrorMessageAtExceptionInService`

Binding: Add Error message to the response message

---

src/Hl7.Fhir.Core/Model/Generated/ValueSet.cs
src/Hl7.Fhir.Core/Model/Generated/_GeneratorLog.cs
src/Hl7.Fhir.STU3.Core/Model/Generated/_GeneratorLog.cs
src/Hl7.Fhir.Support.Poco/Model/Generated/Binary.cs
src/Hl7.Fhir.Support.Poco/Model/Generated/Bundle.cs
src/Hl7.Fhir.Support.Poco/Model/Generated/_GeneratorLog.cs

These changes had been applied manually by MV when designing the new satellite/common projects in 5.0.
This PR includes the (comparable) code generated by our code generator. Again, this should be the same code as the stuff Marco wrote manually, but spacing/ordering might differ.

Move some more classes to common

---

src/Benchmarks/Benchmarks.csproj
src/Hl7.Fhir.Base/Introspection/DeclaredTypeAttribute.cs
src/Hl7.Fhir.Base/Introspection/ModelInspector.cs
src/Hl7.Fhir.Base/Model/Generated/Attachment.cs
src/Hl7.Fhir.Base/Model/Markdown.cs
src/Hl7.Fhir.Base/Properties/AssemblyInfo.cs
src/Hl7.Fhir.Base/Rest/TransactionBuilder.cs
src/Hl7.Fhir.Base/Serialization/FhirJsonBuilder.cs
src/Hl7.Fhir.Base/Serialization/FhirJsonException.cs
src/Hl7.Fhir.Base/Serialization/FhirJsonPocoDeserializer.cs
src/Hl7.Fhir.Base/Serialization/FhirJsonPocoSerializer.cs
src/Hl7.Fhir.Conformance/Properties/AssemblyInfo.cs
src/Hl7.Fhir.Conformance/Specification/Navigation/ElementDefinitionNavigationFunctions.cs
src/Hl7.Fhir.Conformance/Specification/Snapshot/ElementDefnMerger.cs
src/Hl7.Fhir.ElementModel.STU3.Tests/TypedElementToSourceNodeAdapterTests.cs
src/Hl7.Fhir.ElementModel.Shared.Tests/TypedElementToSourceNodeAdapterTests.cs
src/Hl7.Fhir.Serialization.R4.Tests/RoundtripNewSerializers.cs
src/Hl7.Fhir.Serialization.R4.Tests/RoundtripTest.cs
src/Hl7.Fhir.Serialization.R4B.Tests/RoundtripNewSerializers.cs
src/Hl7.Fhir.Serialization.R4B.Tests/RoundtripTest.cs
src/Hl7.Fhir.Serialization.R5.Tests/RoundtripNewSerializers.cs
src/Hl7.Fhir.Serialization.R5.Tests/RoundtripTest.cs
src/Hl7.Fhir.Serialization.Shared.Tests/RoundtripNewSerializers.cs
src/Hl7.Fhir.Serialization.Shared.Tests/RoundtripTest.cs
src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/FhirJsonDeserializationTests.cs
src/Hl7.Fhir.Support.Tests/FhirPath/FhirPathTests.cs
src/Hl7.Fhir.Support.Tests/Serialization/CommonTypeParsingTest.cs
src/Hl7.FhirPath.Tests/Functions/FunctionsTests.cs
src/firely-net-sdk-tests.props
src/firely-net-sdk.props

- ModelInspector.Common => ModelInspector.Base
- FhirModelAssembly for Base is since STU3
- FhirModelAssembly for Conformance is since R4
- Deserializing and Serializing Integer64 with multiple DeclaredTypes
- Update FluentAssertion dependency
- Changed Copyright year
- Bump BenchmarkDotNet from 0.13.3 to 0.13.4
- Implicit Markdown operators can handle null values
- https://github.com/FirelyTeam/fhir-codegen/pull/22

Small corrections

---

src/Hl7.Fhir.Conformance/Model/Generated/ElementDefinition.cs
src/Hl7.Fhir.R5.Tests/Hl7.Fhir.R5.Tests.csproj
src/Hl7.Fhir.STU3/Model/Generated/ElementDefinition.cs
src/Hl7.Fhir.Shared.Tests/ElementModel/PocoTypedElementTests.cs

For the following properties of `ElementDefinition` we've added the `DeclaredType` attribute, because the type has changed in 5.0.0-snapshot3 from `FhirString` to `Markdown`:
- `ElementDefinition.mapping.comment`
- `ElementDefinition.binding.description`
- `ElementDefinition.constraint.requirements`
See also PR: https://github.com/FirelyTeam/fhir-codegen/pull/23

DeclaredType attributes on ElementDefintion properties 

---

src/Hl7.Fhir.Base/Model/Generated/Signature.cs

The datatype `Signature` is now generated by codegen.  Changes:
- `Signature.targetFormat` Added Element since R4
- `Signature.sigFormat` Added Element since R4
- `Signature.data` Renamed from blob to data since R4
- `Signature.contentType` deleted since R4
- `Signature.who` can be a choicetype in STU3 and a reference in R4 and up
- `Signature.onBehalfOf` can be a choicetype in STU3 and a reference in R4 and up
See also PR on codegen: https://github.com/FirelyTeam/fhir-codegen/pull/26

Signature is now generated by codegen

---

src/Hl7.Fhir.Base/Model/Generated/Binary.cs
src/Hl7.Fhir.Base/Model/Generated/Signature.cs

- Some better explanation about `Signature.who` and `Signature.onBehalfOf` (typed changed)
- Better comments when properties are replaced
See also PR https://github.com/FirelyTeam/fhir-codegen/pull/27

Improved comments for some Pocos

---

build/azure-pipelines.yml
build/pipeline-variables.yml

Use a Firely template to push the nuget packages

Devops: Use a Firely template to push the nuget packages

---

build/azure-pipelines.yml

When there is no suffix we would get an error. That is solved now.

Devops: Correction for the NuGet Metapackages version

---

src/Hl7.Fhir.Base/ElementModel/TypedElementExtensions.cs

`TypedElementExtensions.IsExactlyEqualTo()` is now corrected: the `ignoreOrder` was not passed in the recursion
Part of issue #2375

Use ignoreOrder also in the recursion for method IsExactlyEqualTo

---

src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/FhirXmlDeserializationTests.cs

Just added an extra unit test, deserializer already handles the error correctly I believe
fixes #2439

FhirXmlPocoDeserializer handles invalid booleans

---

src/Hl7.Fhir.Base/FhirPath/ElementNavFhirExtensions.cs
src/Hl7.Fhir.Base/FhirPath/FhirEvaluationContext.cs
src/Hl7.Fhir.Shims.STU3AndUp/FhirPath/FhirPathExtensions.cs
src/Hl7.Fhir.Support.Tests/FhirPath/FhirPathTests.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs

Implemented the FhirPath function `memberOf(valueset)`. See also the definition of the function [here](https://hl7.org/fhir/fhirpath.html#functions).
Resolves issue #2404.
The following unittest are made:
- `Hl7.FhirPath.R4.Tests.FhirPathTest.MemberOfTests`
- `Hl7.FhirPath.R4.Tests.FhirPathTest.MemberOfTestsWithoutTerminologyService`
- `Hl7.FhirPath.R4.Tests.FhirPathTest.MemberOfTestWithExampleFromSpecification`

#2404: Implementation of FhirPath function memberOf()

---

src/Hl7.Fhir.Conformance/Specification/Source/Summary/ArtifactSummaryGenerator.cs

In R4 and newer versions, the static property `ArtifactSummaryGenerator.Default` does not function correctly due to an incorrect `ModelInspector`. As this is a static property, it cannot be modified to incorporate a correct ModelInspector. To resolve this issue, end-users should use the constructor `new ArtifactSummaryGenerator(IModelInfo modelInfo)`.
Resolves issue #2411.

#2411: Made the ArtifactSummaryGenerator.Default obsolete

---

src/Hl7.Fhir.Base/FhirPath/Functions/StringOperators.cs
src/Hl7.FhirPath.Tests/Functions/StringFunctionsTests.cs
src/Hl7.FhirPath.Tests/Tests/BasicFunctionTests.cs

Describe the changes in this PR.
Resolves issue #2445
Unit tests added/updated

#2445 Correct split function to not remove empty strings

---

build/azure-pipelines.yml
release-notes.md

We have now the file `release-notes.md`. This file allows us to add extra text specifically intended for inclusion in the release notes. This file will serve as a valuable resource for providing further context and explanations about the release. 
This file will be merged during a release with the solved pull requests to a definite release note document.
Resolves #2457.

#2457: Enhancing automatic generation of release notes

---

build/azure-pipelines.yml
build/pipeline-variables.yml
src/Hl7.Fhir.Base/ElementModel/Types/Quantity.cs
src/Hl7.Fhir.Base/ElementModel/Types/Ucum.cs
src/Hl7.Fhir.Base/Hl7.Fhir.Base.csproj
src/Hl7.Fhir.Support.Tests/ElementModel/EquivalenceTests.cs
src/Hl7.Fhir.Support.Tests/ElementModel/QuantityTests.cs
src/Hl7.Fhir.Support.Tests/ElementModel/UcumTests.cs
src/Hl7.Fhir.Support.Tests/FhirPath/FhirPathTests.cs
src/Hl7.FhirPath.Tests/Functions/OperationsTests.cs

The FhirPath function `comparable()` now utilizes the UCUM library, enabling the comparison of `Quantities` with different units, such as inches and meters.
Moreover, the system type `Quantity` now leverages the UCUM library for performing the comparable function, as well as handling Equality and Equivalence. This enhancement allows for expressions like `1 '[in_i]' > 1 'cm'` in FhirPath, yielding a result of `true`.
Resolves issue #2439.
See the following unit tests:
- QuantityTests
- UcumTests
- EquivalenceTests
- FhirPathTests

#2439: FhirPath comparable() uses UCUMnow

---

src/Hl7.Fhir.Conformance/Model/ValueSet.cs
src/Hl7.Fhir.Conformance/Specification/Terminology/LocalTerminologyService.cs
src/Hl7.Fhir.STU3/Model/ValueSet.cs
src/Hl7.Fhir.STU3/Specification/Terminology/LocalTerminologyService.cs
src/Hl7.Fhir.Specification.STU3.Tests/Terminology/LocalTerminologyServiceTests.cs
src/Hl7.Fhir.Specification.Shared.Tests/Terminology/LocalTerminologyServiceTests.cs

The `ValueSetValidateCode` method in the `LocalTerminologyService` now includes a check to determine if the `Coding.system` references a CodeSystem. If it does not, the method will generate a message to indicate the discrepancy.
Resolves VONK-4618
See unit test `LocalTerminologyServiceTests.CodingWithValuesetAsSystem`

Vonk-4618: LocalTS ValidateCode reports an error for value set reference instead of a code system in coding.system

---

src/Hl7.Fhir.Base/Introspection/ModelInspector.cs
src/Hl7.Fhir.Shared.Tests/Introspection/FhirClassMappingTests.cs

Make sure ForAssembly loads all dependent assemblies, not just base.

2488 Load all dependent FHIR assemblies

---

src/Hl7.Fhir.Base/Validation/CodedValidationException.cs

Corrected a spelling mistake in `CodedValidationException`.
Resolves #2542.

Changed a spelling mistake

---

src/Hl7.Fhir.Base/Specification/Terminology/MimeTypeTerminologyService.cs
src/Hl7.Fhir.Conformance/Specification/Terminology/LocalTerminologyService.cs
src/Hl7.Fhir.Conformance/Specification/Terminology/TerminologyServiceFactory.cs
src/Hl7.Fhir.STU3/Specification/Terminology/LocalTerminologyService.cs
src/Hl7.Fhir.STU3/Specification/Terminology/TerminologyServiceFactory.cs
src/Hl7.Fhir.Specification.STU3.Tests/Terminology/LocalTerminologyServiceTests.cs
src/Hl7.Fhir.Specification.Shared.Tests/Terminology/LocalTerminologyServiceTests.cs

feature: create factory methods for "core" terminology service

---

src/Hl7.Fhir.Conformance/Specification/Terminology/ValueSetExpander.cs
src/Hl7.Fhir.STU3/Specification/Terminology/ValueSetExpander.cs
src/Hl7.Fhir.Specification.STU3.Tests/Source/TerminologyTests.cs
src/Hl7.Fhir.Specification.Shared.Tests/Source/TerminologyTests.cs

fixes https://github.com/FirelyTeam/firely-validator-api/issues/142

Change error message when the ValueSetExpander can't find a specific CodeSystem

---

src/Hl7.Fhir.Base/FhirPath/ElementNavFhirExtensions.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs

Use `string` now as well for a valid input type for the FhirPath function `memberOf()`.
Resolves #2588 
See unit test `TestFhirPathResolve.MemberOfTests`

Use `string` also as a valid type for the input value of `memberOf()`

---

src/Hl7.Fhir.Base/ElementModel/Types/Quantity.cs
src/Hl7.Fhir.Base/ElementModel/Types/Ucum.cs
src/Hl7.Fhir.Support.Tests/ElementModel/QuantityTests.cs
src/Hl7.FhirPath.Tests/Functions/MathOperatorsTests.cs

Added the `Quantity` arithmetic operations, like Add, Substract, Multiply and Divide. These operations can now also be used in FhirPath.
I changed the signature of the not implemented static operators of `Quantity`. Technically is that a breaking change, but here we can get away with it or not?
Resolves #1442.
- Hl7.Fhir.ElementModel.Tests.QuantityTests.ArithmeticOperationsTests
- HL7.FhirPath.Tests.OperationsTests.AssertTestcases

#1442: Added Quantity arithmetic

---

src/Benchmarks/EnumUtilityBenchmarks.cs
src/Hl7.Fhir.Base/Utility/EnumUtility.cs
src/Hl7.Fhir.Support.Tests/Utility/EnumMappingTest.cs

- Improve performance of generic methods in EnumUtility
- Remove usage of ToLowerInvariant for case insensitive parsing in EnumUtility
- Added generic version of GetLiteral and GetSystem methods in EnumUtility
- Added EnumUtility benchmarks
- `ParseLiteral<T>` and `GetName<T>` have an added Enum generic type constraint which is technically a breaking change, but these methods are unlikely to be called with non-Enum generic type parameters.
Resolves #2575.
- Hl7.Fhir.Support.Tests.Utils.EnumMappingTest
- Firely.Sdk.Benchmarks.EnumUtilityBenchmarks
```
BenchmarkDotNet v0.13.8, Windows 11 (10.0.22621.2283/22H2/2022Update/SunValley2)
AMD Ryzen 7 7840U w/ Radeon 780M Graphics, 1 CPU, 16 logical and 8 physical cores
.NET SDK 7.0.401
[Host]     : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT AVX2 …
```

Improve performance of EnumUtility generic methods

---

src/Hl7.Fhir.Base/ElementModel/Types/Date.cs
src/Hl7.Fhir.Base/ElementModel/Types/DateTime.cs
src/Hl7.Fhir.Base/FhirPath/Expressions/SymbolTableInit.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTest.cs

- Add subtract operator for Date and DateTime
- Register FhirPath binary subtract operation for Date and DateTime.
Closes #2599.
Hl7.FhirPath.R4.Tests.FhirPathEvaluatorTest.TestDateTimeArithmetic

Add subtract operator for Date and DateTime.

---

src/Hl7.Fhir.Base/Rest/BaseFhirClient.cs
src/Hl7.Fhir.Base/Rest/TransactionBuilder.cs
src/Hl7.Fhir.Support.Poco.Tests/Rest/FhirClientMockTests.cs

Adds support for the ($process-message)[http://hl7.org/fhir/messageheader-operation-process-message.html] operation used in fhir (messaging)[http://hl7.org/fhir/messaging.html#process].
Resolves #2605
Added unit test.

Add Process message operation

---

src/Hl7.Fhir.Conformance/Specification/Source/SnapshotSource.cs

Internally, SnapshotSource was already using an async resolver, but the constructor still demanded a non-async resolver. This needed to be solved to have the SnapshotSource working in concert with the validator and terminology service.
Fixes #1698.

Add IAsyncResourceResolver support to SnapshotSource

---

src/Hl7.Fhir.Shims.Base/Specification/Terminology/LocalTerminologyService.cs
src/Hl7.Fhir.Specification.Shared.Tests/Source/TerminologyTests.cs

LocalTerminologyService returns original FhirOperationException from getExpandedValueSet

---

src/Hl7.Fhir.Base/Serialization/JsonSerializerOptionsExtensions.cs
src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/FhirJsonSerializationTests.cs

Modify JsonSerializationOptions instead of creating a new instance

---

build/build-variables.yml
build/templates/test-job-template.yml
src/Benchmarks/Benchmarks.csproj
src/Hl7.Fhir.Specification.STU3.Tests/Source/ArtifactSourceTests.cs
src/Hl7.Fhir.Specification.Shared.Tests/Source/ArtifactSourceTests.cs
src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
src/firely-net-sdk-tests.props
src/firely-net-sdk.props

Dropping .NET 6 keeping netstandard2.0, for backwards compatibility

Update solution to .NET 8

---

src/Hl7.Fhir.Base/ElementModel/TypedElementParseExtensions.cs
src/Hl7.Fhir.Base/Model/FhirTypeConstants.cs
src/Hl7.Fhir.Base/Rest/FhirClientSearch.cs
src/Hl7.Fhir.Base/Serialization/DataAnnotationDeserialzationValidator.cs
src/Hl7.Fhir.ElementModel.R4B.Tests/ParseExtensionsTests.cs
src/Hl7.Fhir.ElementModel.R5.Tests/ParseExtensionsTests.cs
src/Hl7.Fhir.ElementModel.Shared.Tests/ParseExtensionsTests.cs
src/Hl7.Fhir.R4B/Model/CodeableReference.cs
src/Hl7.Fhir.R5/Model/CodeableReference.cs

Added code that can extract a CodeableConcept from a CodeableReference, thus extending our capabilities to support CodeableReference as input to the validator.

Support parsing CodeableReference

---

src/Hl7.Fhir.Base/ElementModel/TypedElementParseExtensions.cs

It's wrong, but necessary at this point.

Undo change in visibility

---

src/Hl7.Fhir.Base/Introspection/ModelInspector.cs

A temporary change to ModelInspector so the Base inspectors "knows" about CodeableReference.

Hack ModelInspector so it knows about CodeableReference

---

src/Hl7.Fhir.Base/Serialization/BaseFhirJsonPocoDeserializer.cs

Fix: JSON deserializer should use the known native type when possible when targeting choice types with primitives.
Modifies the Base JSON POCO deserializer to use a known native type as the destination type when there is a choice type with primitives and the target type is in the list.
Fixes #2701 .
Additional unit test locally, @mmsmits pass on full repo.

JSON POCO Deserializer type mapping fix.

---

src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/FhirJsonDeserializationTests.cs

This bug was fixed by PR #2708, but added a test to consolidate this behaviour for future PRs
Closes #2662.
Added test with both deceasedBoolean and deceasedDateTime set

#2662 duplicate choice type entries

---

src/Hl7.Fhir.Base/Rest/BaseFhirClient.cs
src/Hl7.Fhir.Support.Poco.Tests/Rest/FhirClientMockTests.cs

The serialization engine used by an instance of BaseFhirClient (or its derivations) can now be changed in the settings. The new value will decide the engine used by this client. This used to require a new client with the required serialization engine in the constructor.
Closes issue #2661.
Added a unit test which tests whether the serialization engine used by BaseFhirClient matches an expected type

#2661 FhirClient Serialization engine modification

---

src/Hl7.Fhir.Base/Serialization/engine/FhirSerializationEngineFactory.cs
src/Hl7.Fhir.Base/Serialization/engine/PocoSerializationEngine.cs

Redid PocoSerializationEngine.cs constructor to now accept settings objects. Improved ostrich parsing by setting validators to null when creating an ostrich mode parser.
Closes #2463.
Tested using existing round trip tests

#2463 improved ostrich parsing

---

src/Hl7.Fhir.Base/Specification/Source/ZipCacher.cs
src/Hl7.Fhir.Conformance/Specification/Source/CommonZipSource.cs
src/Hl7.Fhir.Specification.Shared.Tests/Source/ZipSourceTests.cs

Rewrote the check on zip file caches to verify the presence of critical files, instead of verifying the existence of the cache. This should hopefully fix issue #2164
Closes #2164
Unable to reproduce the original issue in a unit test. 
note: added a test which verifies the existence of these critical files after a successful run, so that changing the specification will require the cache check to be rewritten with the proper critical files

#2164 reinforce zip cache validity check

---

src/Hl7.Fhir.Base/Specification/Terminology/CustomValueSetTerminologyService.cs
src/Hl7.Fhir.Base/Specification/Terminology/LanguageTerminologyService.cs
src/Hl7.Fhir.Base/Specification/Terminology/MimeTypeTerminologyService.cs
src/Hl7.Fhir.Base/Specification/Terminology/ValueSetTerminologyService.cs

Renamed CodeSystemTerminologyService to be called CustomValueSetTerminologyService to avoid confusion (it only implements validateValueSet, not validateCodeSystem)
none

Renamed CodeSystemTerminologyService for clarity

---

src/Hl7.Fhir.Base/Serialization/PathStack.cs
src/Hl7.Fhir.Support.Poco.Tests/NewPocoSerializers/FhirJsonDeserializationTests.cs

Added edge case check to the resource entering path check for backbone element roots (for use cases such as split bundles)
Resolves #2627.
Tested using the unit test suggested in the issue report. (Create parameter component backbone element, add patient to it, parse the object)

path stack edge case for non-resource root
