- src/Hl7.Fhir.Core/Rest/Requester.cs
In Requester, there is an additional place where HTTP status code needs to be checked. Otherwise, Format Exceptions will occur later. Since there are now 2 places where the status code will have to be checked, I am proposing to also carve the conversion from HTTP status code to an exception into its own method.
> More complete checking of HTTP response codes.

- whats-new.md
Summary for the What's New page.
> Shameless plugs for humble contributions by Tilo.

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core/Model/OperationOutcome.cs
- src/Hl7.Fhir.Core/Rest/Requester.cs
I have added 2 very thorough unit tests and the corresponding code fixes.
> Handle HTTP 4xx/5xx status in combination with OperationOutcome

- build/build.ps1
- build/nuget/Hl7.Fhir.Core/Hl7.Fhir.Core.nuspec
- build/nuget/Hl7.Fhir.Specification/Hl7.Fhir.Specification.nuspec
As discussed on Skype: Changing DSTU2.1 -> DSTU2.
> Fix: DSTU2.1 -> DSTU2

- src/Hl7.Fhir.Core/Hl7.Fhir.Core.Net40.csproj
- src/Hl7.Fhir.Core/Hl7.Fhir.Core.Portable45.csproj
- src/Hl7.Fhir.Core/Model/StructureDefinition.cs
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-cqif-basic-guidance-structure.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-cqif-basic-guidance-trigger.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-encounter-reasoncancelled.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-goal-reasonrejected.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-iso21090-preferred.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-maxvalue.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-minvalue.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-patient-birthtime.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-patient-cadavericdonor.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-patient-clinicaltrial.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-qicore-patient-militaryservice.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-questionnaire-choiceorientation.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-questionnaire-defaultvalue.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-questionnaire-dereference.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-questionnaire-maxlength.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-questionnaire-questioncontrol.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/extension-questionnaire-readonly.xml
- src/Hl7.Fhir.Specification/Specification/Navigation/BaseElementNavigator.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementNavigator.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementNavigatorMovementExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Hallo Ewout,
ik heb de snapshot logica uitgebreid met ondersteuning voor profiles-on-profiles and extension reslicing. Kunnen jij dit mergen en een nieuwe interne NuGet release publiceren? Daarna ga ik Forge bijwerken en kan Ardon dit gaan testen.
[Edit] Tevens een publieke methode ExpandElement toegevoegd t.b.v. Forge, met een aantal unit tests.
> ft-wmr-snapshot-generator

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/ChrisGrenz/extension-structuredefinition-explicit-type-name.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/ChrisGrenz/patient-do-not-call-profile.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/ChrisGrenz/patient-extensions-profile.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/ChrisGrenz/patient-legal-case-lead-counsel-profile.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/ChrisGrenz/patient-legal-case-profile.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/ChrisGrenz/patient-research-authorization-profile.xml
- src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.Net40.csproj
- src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.Net45.csproj
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotRecursionChecker.cs
A couple of improvements:
- Refactor: move recursion checking logic to separate class
- Unit test: add patient profile example by Chris Grenz
- Cosmetic: improve error messages
> Fixed merge

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core.Tests/Validation/ValidateAllExamplesTest.cs
- src/Hl7.Fhir.Core/Model/Generated/RiskAssessment.cs
- src/Hl7.Fhir.Core/Rest/EntryToHttpExtensions.cs
- src/Hl7.Fhir.Core/Rest/FhirClient.cs
- src/Hl7.Fhir.Core/Rest/Requester.cs
- src/Hl7.Fhir.Core/Rest/WebRequestExtensions.cs
This adds support for the compression/decompression using gzip/deflate as discussed.
(only thing might want to not include is the change to test against my server)
> Add support Compression/Decompression using gzip/deflate

- src/Hl7.Fhir.Core/FluentPath/PocoNavigatorExtensions.cs
Create an extension method that will convert fhir values into fhir values (as not all results will be - such as those returned from an exists() function)
(This was already in the STU3 branch, but hadn't been merged back into this stream)
> Handle conversion of fluentpath values to fhir values.

- src/Hl7.Fhir.Core/Model/Code.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Core/Support/NullExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
Also implement helper method IsCoreModelTypeUri
> Develop - add IStringValue interface to Code

- src/Hl7.Fhir.Core.Tests/Model/AnnotationTests.cs
- src/Hl7.Fhir.Core/Model/Base.cs
includes HasAnnotation and SetAnnotation helper methods
> Annotation support for non class types.

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Net45.Tests.csproj
- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core.Tests/TestData/valueset-group-type-human.xml
- src/Hl7.Fhir.Core.Tests/TestData/valueset-v2-0717.json
- src/Hl7.Fhir.Specification.Tests/SnapshotElementMatcherTests.cs
- src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementNavigatorSlicingExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
bugfix: merge child constraints of of slicing entry
> Develop - Snapshot Generator bugfix: merge child constraints of of slicing entry

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Net45.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Ardon/nl-core-address.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Ardon/nl-core-organization.xml
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
> Bug fixes for DirectoryResolver & SnapshotGenerator

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/TestDataVersionCheck.cs
- src/Hl7.Fhir.Core/FhirPath/PocoNavigator.cs
- src/Hl7.Fhir.Core/FhirPath/PocoNavigatorExtensions.cs
- src/Hl7.Fhir.Specification.Tests/SpecificationTestDataVersionCheck.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementDefinitionNavigator.cs
No changes to the actual validator code, just some more tests enabled, stub for the htmlchecks() fhirpath function, and an update to the elementDefinition debugger display
> Develop stu3 validation work in progress

- src/Hl7.Fhir.Core.Tests/TestData/BGZ AllergyIntolerance - Example.xml
- src/Hl7.Fhir.Core.Tests/TestData/example.noAuditEvent-accessPatientRecord.xml
- src/Hl7.Fhir.Core.Tests/TestData/example.noAuditEvent-login.xml
- src/Hl7.Fhir.Core.Tests/TestData/valueset-group-type-human.xml
- src/Hl7.Fhir.Core.Tests/TestDataVersionCheck.cs
All unit test data now updated to STU3 (not verified, but all now serializing correct - and seem ok from the manual update)
Valueset has local content - did not create an actual codesystem underneath it, and the SD content was updated using my migrator util
> Develop stu3 - untit test data updates

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.csproj
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotBaseComponentGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> bugfix - Snapshot generator - fix invalid initialization of ElementDefinition.Base component

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementIdGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
TODO: Test in Forge, verify fix (?)
> bugfix: SnapshotGenerator - fix invalid ElementId initialization (?)

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/SearchAsyncTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core/Rest/EntryToHttpExtensions.cs
- src/Hl7.Fhir.Core/Rest/FhirClientSearch.cs
- src/Hl7.Fhir.Core/Rest/IFhirClient.cs
- src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs
PR for issue #479.
Added methods for executing search using POST
Can be tested by using end point at http://nde-fhir-ehelse.azurewebsites.net/fhir
> WIP: Support search using POST

- src/Hl7.Fhir.Specification.Tests/Snapshot/InMemoryProfileResolver.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/TimingSource.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/SummarySourceTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
- src/Hl7.Fhir.Specification/Specification/Source/IConformanceSource.cs
- src/Hl7.Fhir.Specification/Specification/Source/ISummarySource.cs
- src/Hl7.Fhir.Specification/Specification/Source/ZipSource.cs
Introduce new interface ISummarySource
> feature: #543 - Remove ListSummaries() from IConformanceSource

- src/Hl7.FhirPath.Tests/Tests/FhirPathTest.cs
- src/Hl7.FhirPath/FhirPath/Functions/CollectionOperators.cs
> feature: FhirPath is now able to handle Resource.* and DomainResource.* expressions

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/DifferentialTreeConstructor.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> feature #601: make the DifferentialTreeConstructor class public

- src/Hl7.Fhir.Core/Model/Canonical.cs
- src/Hl7.Fhir.Core/Model/Generated/Canonical.cs
- src/Hl7.Fhir.Core/Model/Generated/FhirBoolean.cs
- src/Hl7.Fhir.Core/Model/Generated/Template-DataTypeModel.cs
- src/Hl7.Fhir.Core/Model/Generated/Template-DataTypeModel.tt
> fix: Boolean's value prop should not have [BooleanPattern]

- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Model/Element.cs
> fix: changed IsSummary to false for element Extension

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/HttpUtilTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core/Rest/EntryToHttpExtensions.cs
- src/Hl7.Fhir.Core/Rest/HttpUtil.cs
- src/Hl7.Fhir.Core/Rest/Requester.cs
- src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs
> fix: there are no absolute url's anymore in Bundle entries

- src/Hl7.Fhir.Specification.Tests/Source/ResourceResolverTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/WebResolver.cs
Couple of small improvements to the WebResolver class
> fix: #667 Improve WebResolver

- src/Hl7.Fhir.Core/Support/CanonicalUrlConflictException.cs
- src/Hl7.Fhir.Core/Support/ResolvingConflictException.cs
- src/Hl7.Fhir.Specification.Tests/Source/ResourceResolverTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
- src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryExtensions.cs
- src/Hl7.Fhir.Specification/Support/ResolvingConflictException.cs
Don't throw while indexing directory; instead, throw when resolving conflicting url
> feature: #393 DirectorySource - Improve handling of resolving conflicts

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
Found a possible race condition in a test that would parrallelize validation - but accidentally re-used the validator across threads. Should fix the build/test failure that occurs occasionally on the CI build.
> fix: parallel-test should not reuse validator (stu3 only)

- README.md
- src/Hl7.Fhir.Core.Tests/ElementModel/PocoNavigatorTests.cs
- src/Hl7.Fhir.Core/ElementModel/PocoElementNode.cs
- src/fhir-net-api.props
Merge recent changes to dstu2 into stu3 to sync both versions
> Update STU3 with DSTU2 changes.

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Rest/FhirClientSearch.cs
- src/Hl7.Fhir.Core/Serialization/FhirJsonParser.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlParser.cs
Merge recent changes to DSTU2 into STU3
> Merge DSTU2 changes to STU3

- src/Hl7.Fhir.Core/FhirPath/ElementNavFhirExtensions.cs
- src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
- src/Hl7.FhirPath.Tests/Tests/FhirPathTest.cs
- src/Hl7.FhirPath/FhirPath/EvaluationContext.cs
- src/Hl7.FhirPath/FhirPath/Expressions/SymbolTableInit.cs
- src/Hl7.FhirPath/FhirPath/Functions/UtilityOperators.cs
Add minimal set of new FhirPath (normative) functions to be able to run R4 invariants.
> Add normative FhirPath functions

- src/Hl7.Fhir.Core/Model/Source/profiles-others.xml
- src/Hl7.Fhir.Core/Model/Source/profiles-types.xml
- src/Hl7.Fhir.Core/Model/Source/search-parameters.xml
- src/Hl7.Fhir.Specification/data/extension-definitions.xml
- src/Hl7.Fhir.Specification/data/profiles-others.xml
- src/Hl7.Fhir.Specification/data/profiles-types.xml
- src/Hl7.Fhir.Specification/data/search-parameters.xml
Correct ele-1 to use 'or' instead of incorrect '|'
Search parameters: correct value.as(DateTime) to value.as(dateTime)
> fix: replaced | by 'or' and as(DateTime) by as(dateTime)

- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Rest/SearchParams.cs
- src/Hl7.Fhir.Core/Serialization/BaseFhirSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
- src/Hl7.Fhir.ElementModel/MaskingNode.cs
Added another parameter:elements in serialization method. Added necessary logic to configure the serialization around the new parameter. Unit Test method for the new scenarios.
> serialization add support for _elements #460

- src/Hl7.Fhir.Core/Support/DateExtensions.cs
- src/Hl7.FhirPath.Tests/Tests/FhirPathTest.cs
Merge changes to DSTU2 forward to STU3
> Sync DSTU2 with STU3

- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Rest/SearchParams.cs
- src/Hl7.Fhir.Core/Serialization/BaseFhirSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
- src/Hl7.Fhir.ElementModel/MaskingNode.cs
Added another parameter:elements in serialization method. Added necessary logic to configure the serialization around the new parameter. Unit Test method for the new scenarios.
> Merge 460 to stu3

- src/Hl7.Fhir.Specification.Tests/Source/ResourceResolverTests.cs
- src/Hl7.Fhir.Specification.Tests/TestData/validation/patient-telecom-reslice-ek.xml
- src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryHarvesters.cs
> Using version in canonical urls #578

- src/Hl7.Fhir.Core.Tests/Model/DateTimeOperatorTests.cs
- src/Hl7.Fhir.Core/Model/FhirDateTime.cs
> Make ToDateTimeOffset obsolete in case of nullable Timespan

- src/Hl7.FhirPath.Tests/Tests/AssertParser.cs
- src/Hl7.FhirPath.Tests/Tests/FhirPathGrammarTest.cs
- src/Hl7.FhirPath.Tests/Tests/FhirPathLexerTest.cs
- src/Hl7.FhirPath/FhirPath/FhirPathCompiler.cs
- src/Hl7.FhirPath/FhirPath/IValueProviderFPExtensions.cs
- src/Hl7.FhirPath/FhirPath/Parser/Grammar.cs
- src/Hl7.FhirPath/FhirPath/Parser/Lexer.cs
- src/Hl7.FhirPath/FhirPath/Parser/Operators.cs
- src/Hl7.FhirPath/Sprache/CommentParser.cs
- src/Hl7.FhirPath/Sprache/IComment.cs
- src/Hl7.FhirPath/Sprache/IInput.cs
- src/Hl7.FhirPath/Sprache/IPositionAware.cs
- src/Hl7.FhirPath/Sprache/IResultOfT.cs
- src/Hl7.FhirPath/Sprache/Input.cs
- src/Hl7.FhirPath/Sprache/Option.cs
- src/Hl7.FhirPath/Sprache/Parse.Optional.cs
- src/Hl7.FhirPath/Sprache/Parse.Positioned.cs
- src/Hl7.FhirPath/Sprache/Parse.Primitives.cs
- src/Hl7.FhirPath/Sprache/Parse.Regex.cs
- src/Hl7.FhirPath/Sprache/Parse.Sequence.cs
- src/Hl7.FhirPath/Sprache/Parse.cs
- src/Hl7.FhirPath/Sprache/ParseException.cs
- src/Hl7.FhirPath/Sprache/ParserOfT.cs
- src/Hl7.FhirPath/Sprache/Position.cs
- src/Hl7.FhirPath/Sprache/Result.cs
- src/Hl7.FhirPath/Sprache/ResultHelper.cs
- src/Hl7.FhirPath/Sprache/StringExtensions.cs
> fix: renamed namespace Sprache to Hl7.FhirPath.Sprache in order to avoid compiling conflicts

- .gitignore
- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core/Model/DomainResource.cs
> feature: adding helper method FindContainedResource on DomainResource

- README.md
- contributors.md
no code fix here, only update the readme.md and contributors.md
> fix: updated the docs with R4 info inside the repo

- src/Hl7.FhirPath.Tests/PocoTests/FhirPathEvaluatorTest.cs
- src/Hl7.FhirPath.Tests/TestData/fhirpath/csharp-tests.xml
- src/Hl7.FhirPath/FhirPath/Functions/StringOperators.cs
Cherry pick changes made to FHIRPath index() implementation in STU3 to R4.
> 807-FHIRPath-indexOf-spec-change R4

- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Serialization/FhirJsonBuilder.cs
> Fixes Json serializer returning instead of continuing when encountering an empty object

- src/Hl7.Fhir.ElementModel/TypedElementNode.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonTyped.cs
Added the context to the error message. Created a Test for the ToTypedElement method when the resource has an unknown element.
> Made the Error a bit more clear.

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotElementMatcherTests.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotSourceTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Update snapshot generator to support changed behavior in R4 concerning choice type constraints.
> fix: #824 Implement R4 Choice Type Constraints

- src/Hl7.Fhir.Specification.Tests/Snapshot/DebugExtensions.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotBaseComponentGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Fix for issue #853 R4 Snapshot Generator - Fix ElementDefinition.Base component
> #853 R4 Snapshot Generator - Fix ElementDefinition.Base component

- LICENSE
- src/Hl7.Fhir.Core/ElementModel/PocoBuilder.cs
- src/Hl7.Fhir.Core/Serialization/ComplexTypeReader.cs
- src/Hl7.Fhir.Core/Serialization/DispatchingReader.cs
- src/Hl7.Fhir.Core/Serialization/PrimitiveValueReader.cs
- src/Hl7.Fhir.Core/Serialization/ResourceReader.cs
- src/Hl7.Fhir.ElementModel/TypedElementNode.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonTyped.cs
- src/Hl7.Fhir.Serialization/FhirJsonNode.cs
- src/Hl7.Fhir.Serialization/FhirXmlBuilder.cs
- src/Hl7.Fhir.Serialization/FhirXmlNode.cs
- src/Hl7.Fhir.Serialization/FhirXmlSerializationSettings.cs
- src/fhir-net-api.props
Pulling in a batch of minor DSTU2 changes into STU3
> Forward minor DSTU2 changes into STU3

- src/Hl7.Fhir.Core.Tests/FhirPathExtensionsTest.cs
- src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/ScopedNodeTests.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatient.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonTyped.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonUntyped.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientXmlTyped.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientXmlUntyped.cs
- src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientJson.cs
- src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientXml.cs
- src/Hl7.Fhir.Serialization.Tests/SerializePartialTree.cs
- src/Hl7.Fhir.Serialization.Tests/StreamJsonResources.cs
- src/Hl7.Fhir.Serialization.Tests/StreamXmlResources.cs
- src/Hl7.Fhir.Serialization.Tests/SummaryTests.cs
- src/Hl7.Fhir.Specification.Tests/JTokenExtensionsTests.cs
- src/Hl7.Fhir.Specification.Tests/JsonNavigatorTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSourceTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ResourceResolverTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/ProfileAssertionTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/SchemaCollectionTest.cs
- src/Hl7.FhirPath.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
- src/fhir-net-api.targets
Direct port of the DSTU2 PR (#846)
> Enable cross-platform development (STU3)

- src/Hl7.FhirPath.Tests/PocoTests/FhirPathEvaluatorTest.cs
- src/Hl7.FhirPath.Tests/TestData/fhirpath/csharp-tests.xml
- src/Hl7.FhirPath/FhirPath/Expressions/SymbolTableInit.cs
- src/Hl7.FhirPath/FhirPath/Functions/StringOperators.cs
No related issue here : maintenance
> feature: copied FhirPath project from R4 to DSTU2

- src/Hl7.Fhir.Core/ElementModel/PocoBuilderSettings.cs
- src/Hl7.Fhir.Core/FhirPath/FhirEvaluationContext.cs
- src/Hl7.Fhir.Core/Rest/HttpToEntryExtensions.cs
- src/Hl7.Fhir.Core/Serialization/ParserSettings.cs
- src/Hl7.Fhir.Core/Serialization/SerializerSettings.cs
- src/Hl7.Fhir.ElementModel/MaskingNodeSettings.cs
- src/Hl7.Fhir.ElementModel/TypedElementSettings.cs
- src/Hl7.Fhir.Serialization/FhirJsonParsingSettings.cs
- src/Hl7.Fhir.Serialization/FhirJsonSerializationSettings.cs
- src/Hl7.Fhir.Serialization/FhirXmlParsingSettings.cs
- src/Hl7.Fhir.Serialization/FhirXmlSerializationSettings.cs
- src/Hl7.Fhir.Serialization/JsonNavigatorStream.cs
- src/Hl7.Fhir.Serialization/NavigatorStreamFactory.cs
- src/Hl7.Fhir.Serialization/XmlNavigatorStream.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
- src/Hl7.Fhir.Specification/Specification/Source/DirectorySourceSettings.cs
- src/Hl7.Fhir.Specification/Specification/Source/WebResolver.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpanderSettings.cs
- src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs
- src/Hl7.FhirPath/FhirPath/Expressions/SymbolTableInit.cs
Update STU3 with DSTU2 changes
> Update STU3 with DSTU2 changes

- src/Hl7.Fhir.Core/ElementModel/PocoBuilder.cs
- src/Hl7.Fhir.ElementModel/ElementNodeExtensions.cs
- src/Hl7.Fhir.ElementModel/IElementNavigator.cs
- src/Hl7.Fhir.ElementModel/SourceNodeExtensions.cs
* Updated outdated obsolete messages referring to IElementNode, changed to
ITypedElement
> Update outdated obsolete message

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Core.Tests/Model/ValidateAllExamplesSearchExtractionTest.cs
- src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/DefaultModelFactoryTest.cs
- src/Hl7.Fhir.Core/ElementModel/PocoElementNode.cs
- src/Hl7.Fhir.Core/ElementModel/PocoNavigator.cs
- src/Hl7.Fhir.Core/Model/Element.cs
- src/Hl7.Fhir.Core/Model/ElementValue.cs
- src/Hl7.Fhir.Core/Model/Extension.cs
- src/Hl7.Fhir.Core/Model/Narrative.cs
- src/Hl7.Fhir.Core/Serialization/DefaultModelFactory.cs
- src/Hl7.Fhir.Core/Specification/PocoStructureDefinitionSummaryProvider.cs
- src/Hl7.Fhir.ElementModel/ElementDefinitionSummaryCache.cs
- src/Hl7.Fhir.Serialization.Tests/RoundtripTest.cs
- src/Hl7.Fhir.Serialization/FhirJsonNode.cs
- src/Hl7.Fhir.Serialization/FhirXmlNode.cs
- src/Hl7.FhirPath/FhirPath/Expressions/DynaDispatcher.cs
Did some profiling to improve the speed of serialization/deserialization
> Several performance improvements

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Core.Tests/Model/ValidateAllExamplesSearchExtractionTest.cs
- src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/DefaultModelFactoryTest.cs
- src/Hl7.Fhir.Core/ElementModel/PocoElementNode.cs
- src/Hl7.Fhir.Core/ElementModel/PocoNavigator.cs
- src/Hl7.Fhir.Core/Model/Element.cs
- src/Hl7.Fhir.Core/Model/ElementValue.cs
- src/Hl7.Fhir.Core/Model/Extension.cs
- src/Hl7.Fhir.Core/Model/Narrative.cs
- src/Hl7.Fhir.Core/Serialization/DefaultModelFactory.cs
- src/Hl7.Fhir.Core/Specification/PocoStructureDefinitionSummaryProvider.cs
- src/Hl7.Fhir.ElementModel/ElementDefinitionSummaryCache.cs
- src/Hl7.Fhir.Serialization.Tests/RoundtripTest.cs
- src/Hl7.Fhir.Serialization/FhirJsonNode.cs
- src/Hl7.Fhir.Serialization/FhirXmlNode.cs
- src/Hl7.FhirPath/FhirPath/Expressions/DynaDispatcher.cs
Several perf improvements were pulled into /develop, but are useful for the upcoming 1.2 release too.
> PR to integrate performance improvements from develop into 1.2.0 release

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/TestData/CustomBasic-StructureDefinition-R3.json
- src/Hl7.Fhir.Specification.Tests/Validation/CustomResourceValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/ProfileAssertion.cs
- src/Hl7.Fhir.Specification/Validation/ProfilePreprocessor.cs
- src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
Added the Resource type name mapper delegate for custom types in Profile Assertion and Preprocessor.
Added a IsInstanceFor method in ProfileAssertion.cs to deal differently with the Custom types.
> Validate custom resource

- src/Hl7.Fhir.ElementModel/TypedElementOnSourceNode.cs
#968 
Added location to the error message and update the references to this method.
> Parse error does not indicate location

- src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/DirectorySource.cs
Fix for the DirectorySource.Refresh() method to also update summaries for existing resource files that have changed.
> fix: #989 DirectorySource.Refresh() update summaries of changed files

- src/Hl7.Fhir.Core/Model/QuestionnaireResponse.cs
#991 Additional/improved debugger displays for Questionnaire/Questionnaire response resource types.
> #991 include/improve debugger displays

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/BatchValidationExtensions.cs
#736 
#594 
Removed the unnecessary issues when the condition has been met. Added a specific unit test for it.
> Validator informational messages skipped

- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Core/Rest/SearchParams.cs
_sort did not allow the use of underscore search parameter such as '_lastUpdated'
> CP of #1003 for STU3

- src/Hl7.Fhir.Core.Tests/PocoNavigatorTests.cs
- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.Fhir.ElementModel/ElementNode.cs
- src/Hl7.Fhir.ElementModel/IShortPathGenerator.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/BatchValidationExtensions.cs
Integrate recent STU3 PRs into R4
> Integrate recent STU3 PRs into R4

- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.Fhir.ElementModel/DomNode.cs
- src/Hl7.Fhir.ElementModel/ElementNode.cs
- src/Hl7.Fhir.ElementModel/PrimitiveElement.cs
- src/Hl7.Fhir.Support.Tests/PrimitiveTests.cs
- src/Hl7.Fhir.Support/Model/Coding.cs
- src/Hl7.Fhir.Support/Model/Primitives.cs
- src/Hl7.Fhir.Support/Utility/Cache.cs
- src/Hl7.Fhir.Support/Utility/DictionaryUtilities.cs
- src/Hl7.Fhir.Support/Utility/ExceptionSourceExtensions.cs
- src/Hl7.Fhir.Support/Utility/ExceptionSourcing.cs
- src/Hl7.Fhir.Support/Utility/PredicateExtensions.cs
- src/Hl7.Fhir.Support/Utility/PropertyInfoExtensions.cs
- src/Hl7.FhirPath/FhirPath/Expressions/ExpressionNode.cs
- src/Hl7.FhirPath/FhirPath/TypeInfo.cs
The implementation of the Mapping Engine required some additional functionality, mostly new functions on ElementNode.
> Updates for Mapping Engine

- src/Hl7.Fhir.ElementModel/TypedElementOnSourceNode.cs
Got lost because of a manual action due to rename of the file
> fix: redid changes from Argument to Format exception in ElementNode

- src/Hl7.FhirPath/FhirPath/Expressions/ExpressionNode.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/ISourcePositionInfo.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/OutputEventArgs.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/Source.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/SourceBreakpoint.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/StackFrame.cs
This adds basic infrastructure for the debugging features of the mapping language engine.
> feature: added Location to all expression nodes.

- src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
- src/Hl7.Fhir.Core/Serialization/SerializerSettings.cs
- src/Hl7.Fhir.ElementModel/TypedElementOnSourceNode.cs
- src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientJson.cs
- src/Hl7.Fhir.Serialization.Tests/SerializeDemoPatientXml.cs
- src/Hl7.Fhir.Serialization/FhirJsonBuilder.cs
- src/Hl7.Fhir.Serialization/FhirJsonBuilderExtensions.cs
- src/Hl7.Fhir.Serialization/FhirJsonSerializationSettings.cs
- src/Hl7.Fhir.Serialization/FhirXmlBuilderExtensions.cs
- src/Hl7.Fhir.Serialization/FhirXmlSerializationSettings.cs
- src/Hl7.Fhir.Serialization/Utility/SerializationUtil.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Schema/Binding.cs
- src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
- src/Hl7.FhirPath/FhirPath/Expressions/ExpressionNode.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/ISourcePositionInfo.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/OutputEventArgs.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/Source.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/SourceBreakpoint.cs
- src/Hl7.FhirPath/FhirPath/Language/Debugging/StackFrame.cs
> Update r4 with stu3 changes

- src/Hl7.Fhir.ElementModel/PrimitiveElement.cs
> fix: function ToString(0 was in R4, but not in STU3 yet

- src/Hl7.Fhir.ElementModel.Tests/SourceNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/IssuesTests.cs
- src/Hl7.Fhir.Support.Tests/EnumMappingTest.cs
- src/Hl7.Fhir.Support.Tests/Hl7.Fhir.Support.Tests.csproj
- src/Hl7.Fhir.Support.Tests/Utils/JsonAssert.cs
Equivalent to the DSTU2 PR with the same name.
> feature: removed dependencies on POCO's in support unit tests (STU3)

- src/Hl7.Fhir.ElementModel.Tests/SourceNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs
- src/Hl7.Fhir.ElementModel/PrimitiveElement.cs
- src/Hl7.Fhir.Specification.Tests/Validation/IssuesTests.cs
- src/Hl7.Fhir.Support.Tests/EnumMappingTest.cs
- src/Hl7.Fhir.Support.Tests/Hl7.Fhir.Support.Tests.csproj
- src/Hl7.Fhir.Support.Tests/Utils/JsonAssert.cs
Update R4 with latest changes to STU3 branch
> Update R4 with latest changes to STU3 branch

- Hl7.Fhir.sln
> fix: in release mode -> no build of testprojects

- src/Hl7.Fhir.Core.Tests/TestDataHelper.cs
- src/Hl7.FhirPath.R4.Tests/Hl7.FhirPath.R4.Tests.csproj
- src/Hl7.FhirPath.R4.Tests/PocoTests/ConverterExtensions.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathExtensionsTest.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathScaleTest.cs
- src/Hl7.FhirPath.R4.Tests/TestData/Large-QuestionnaireResponse.xml
- src/Hl7.FhirPath.R4.Tests/TestData/bundle-contained-references.xml
Moved some tests from the Core tests to the FhirPath tests for R4.
> rewrite: moved tests to common.r4

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/DifferentialTreeConstructor.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGeneratorAnnotations.cs
Sync PR #1069 from develop-stu3 to 1.x/stu3
> Sync PR #1069 from develop-stu3 to 1.x/stu3

- src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
...as long as there is a single slice
> Now supports slices along a discriminator (stu3)

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/SpecificationTestDataVersionCheck.cs
- src/Hl7.Fhir.Specification.Tests/TestData/validation/list-with-profile-slicing.xml
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/BindingDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/BucketFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/PathBasedDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/PatternDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ProfileDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/TypeDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ValueDiscriminator.cs
Removed some code duplication, added support for 'profile' slicing, fixed unit-tests.
> Add profile slicing stu3

- src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
Related to this PR ( https://github.com/FirelyTeam/fhir-net-common/pull/7 ) that fixes the #1071 problem.
> Added unit test for 1071 fix.

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/DifferentialTreeConstructor.cs
This PR solves issue #1101 for stu3
> fix: #1101 Handle element constraint without a path [STU3]

- src/Hl7.Fhir.Core.Tests/Serialization/ValueQuantityParsingTests.cs
- src/Hl7.Fhir.Core/Introspection/ModelInspector.cs
Fix: SimpeQuantity was treated by ModelInspector as FhirType and because of that the Quantity type was replaced in the "dataTypeClass" by SimpleQuantity.
> Fix: 999 SimpleQuantity issue

- src/Hl7.Fhir.Core/Rest/FhirClient.cs
#1129 
Some operations might return other success status codes than 200, I Included the requested ones and also Accepted (202).
> Added more expected status' for Fhir Client Operation

- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core/Rest/HttpUtil.cs
> fix: Remove Uri.ToString - encode url

- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
#951 #943 
Reverted some changes from a previous commit, as gForge clarification contradicted our interpretation.
> Fix: update ModelInfo after gForge clarification

- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Core/Rest/HttpUtil.cs
- src/Hl7.Fhir.Core/Rest/WebRequestExtensions.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
- src/Hl7.Fhir.Core/Serialization/SerializerSettings.cs
- src/Hl7.Fhir.Core/Support/DateExtensions.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/ProfileAssertionTests.cs
- src/Hl7.Fhir.Specification/Validation/TypeRefValidationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
- src/fhir-net-api.props
Merge the changes from `develop-1.x/stu3` to `develop-1.x/r4`. Preparing for release 1.5.0-beta
> Forward merge from develop-1.x/stu3

- src/Hl7.Fhir.Core.Tests/Validation/ValidateAllExamplesTest.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
- src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.csproj
Forward merge from develop-1.x/stu3 to develop-1.x/r4 after technical correction 3.0.2
> Feature/forward merge from develop1.x stu3

- src/Hl7.Fhir.Core/Specification/PocoStructureDefinitionSummaryProvider.cs
- src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
> Bugfix/1192 Add DefaultTypeName for StructureDefinitionSummaryProvider

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/George Stoian/MyBase.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/George Stoian/MyDerivedPatient.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/George Stoian/MyHumanName.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/George Stoian/MyPatient.xml
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
#1168 
Added a new check to generate the snapshot for a referenced SD when it is loaded.
> Snapshot generator does not auto generate referenced snapshots it depends on

- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs
- src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs
Forward merge with the following PR's:
- #1175 
- #1222
> Forward merge from stu3: PR 1175 and 1222

- src/Hl7.Fhir.Core.Tests/Rest/TransactionBuilderTests.cs
- src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs
- src/Hl7.Fhir.ElementModel.Tests/TypedElementToSourceNodeAdapterTests.cs
Forward merge with the following PR's:
#1175
#1222
> Forward merge from R4: PR 1175 and 1222

- src/Hl7.Fhir.Specification.Tests/Validation/IssuesTests.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs
#1244: added FhirPath unit tests
> Added FhirPath Unit tests for issue 1244

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
> fixes: Unit test validate cardinality 

- src/Hl7.Fhir.Core/Model/ElementDefinitionExtensions.cs
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/BindingDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/CombinedDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/PathBasedDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/PatternDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ProfileDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/TypeDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ValueDiscriminator.cs
> feature: #1246 allow combinations of fixed/pattern/binding for value and pattern discriminators

- src/Hl7.Fhir.Specification.Tests/PocoSerializationInfoTests.cs
- src/Hl7.Fhir.Specification.Tests/SerializationInfoTestsHelpers.cs
- src/Hl7.Fhir.Specification.Tests/StructureDefinitionSerializationInfoTests.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementDefinitionNavigator.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Source/ResourceResolverExtensions.cs
- src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
> 1316 - Raise an explicit error when a snapshot is required

- src/Hl7.Fhir.Core/Model/ElementDefinitionExtensions.cs
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/ChildConstraintValidationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/BindingDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/CombinedDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/PathBasedDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/PatternDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ProfileDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/TypeDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ValueDiscriminator.cs
> feature: [R4] #1246 allow combinations of fixed/pattern/binding for value and pattern discriminators

- README.md
> fix: change link to release pages and add R5 as a package to

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
> #1140 - added unit test for primitive profiles with eld-13

- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTest.cs
> Added a unit-test to prove #1140 [R4]

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
> fix: 1302, error in StructureDefinition.Differential, sdf-8

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Removed extensions inheritance of root elements in StructureDefinition snapshotting
> #1325 - Removed extensions inheritance of root elements in a StructureDefinition

- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Core/Rest/FhirClient.cs
> Client now checks for minor version compatible version of the server instead of an exact match

- README.md
- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Core/Rest/FhirClient.cs
- src/Hl7.Fhir.Serialization.Tests/Hl7.Fhir.Serialization.Tests.csproj
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientJsonUntyped.cs
- src/Hl7.Fhir.Serialization.Tests/ParseDemoPatientXmlTyped.cs
- src/Hl7.Fhir.Serialization.Tests/TestData/no-namespace.xml
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/PocoSerializationInfoTests.cs
- src/Hl7.Fhir.Specification.Tests/SerializationInfoTestsHelpers.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/StructureDefinitionSerializationInfoTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementDefinitionNavigator.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
- src/Hl7.Fhir.Specification/Specification/Source/ResourceResolverExtensions.cs
- src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
- src/Hl7.Fhir.Specification/Validation/OperationOutcomeExtensions.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/CombinedDiscriminator.cs
This is a forward merge from develop-1.x/stu3 to develop-1.x/r4
> Update develop-1.x/r4 with develop-1.x/stu3

- Hl7.Fhir.sln
- src/fhir-net-api.props
> Updated compiler for the core projects to use C# 8.0 (For R3)

- Hl7.Fhir.sln
- src/fhir-net-api.props
(cherry picked from commit 42359c07d60487c7e2d3714ddd59542e5e30af7e)
> Updated compiler for the core projects to use C# 8.0 (For R4)

- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotBaseComponentGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Source/ResourceResolverExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Source/SnapshotSource.cs
- src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpander.cs
Made sure we call ConfigureAwait(false) everywhere. Also includes a temp fix for SDSummaryProvider.Provide.
> Add configure await & temp fix provider (for R4) 

- Hl7.Fhir.sln
- src/fhir-net-api.props
> feature: updated compiler for the core projects to use C#8.0

- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
Enums will be treated as System.Code primitives
> Added test to verify enums can now be used as primitive values (for R3)

- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTest.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
Enums will be treated as System.Code primitives
> Added test to verify enums can now be used as primitive values (for R4) 

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
> New slice to derived profile with slicing

- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Core/Model/IConformanceResource.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
Update 1.x/r4 with changes from 1.x/stu3
> update 1.x-r4 with 1.x-stu3

- Hl7.Fhir.sln
- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Core/Model/IConformanceResource.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/fhir-net-api.props
Branch 1.x/r5 is updated with changes from branch 1.x/r4
> Update 1.x/r5 from 1.x/r4

- src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/DiscriminatorInterpreter.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTest.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTestFromSpec.cs
- src/Hl7.FhirPath.R4.Tests/TestData/fhirpath/csharp-tests.xml
Chapter 5 of FhirPath N1 (http://hl7.org/fhirpath/N1/#functions) has been checked and code is now following this specification
> FhirPath to Normative - Chapter 5

- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Core/Model/IConformanceResource.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
> Sync develop1.x/r4 to develop-r4

- src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
- src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.csproj
- src/fhir-net-api.props
The previous configuration did not work for Release
> Change the configuration of targetframeworks

- src/Hl7.Fhir.Core.Tests/FhirPathExtensionsTest.cs
> Implement $index in FHIRPath

- src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Core/Serialization/ComplexTypeReader.cs
> Fix 808: unify Format and StructuralTypeException (for R3)

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/QueryParserTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/ResourceParsingTests.cs
- src/Hl7.Fhir.Core/FhirPath/FhirEvaluationContext.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Core/Rest/BundleToEntryRequest.cs
- src/Hl7.Fhir.Core/Rest/FhirClientSearch.cs
- src/Hl7.Fhir.Core/Rest/SearchParamsExtensions.cs
- src/Hl7.Fhir.Core/Serialization/ComplexTypeReader.cs
- src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
We've had a few STU3-only PRs that were trivial enough to not have an R4 counterpart.  Merge these changes in one sweep into R4.
> Sync R3 changes into R4

- src/Hl7.Fhir.Core.Tests/FhirPathExtensionsTest.cs
- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpander.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpanderSettings.cs
Update branch `develop-1.x\r4` with `develop-1.x\stu3`
> Feature/update 1.x r4 from 1.x stu3

- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/HttpUtilTests.cs
- src/Hl7.Fhir.Core.Tests/Rest/PatchExtensionsTest.cs
- src/Hl7.Fhir.Core.Tests/Rest/RequesterTests.cs
- src/Hl7.Fhir.Core/Model/Parameters.cs
- src/Hl7.Fhir.Core/Model/PatchParametersExtensions.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Core/Rest/BundleToEntryRequest.cs
- src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs
add patch and conditional patch to the FHIR Client
> feature: add Patch functionality to FHIR client

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientTests.cs
> client: test multiple message handlers

- src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/DiscriminatorInterpreter.cs
Update develop-r4 with develop-r3
> Update develop-r4 with develop-r3 (forward merge) 

- src/Hl7.Fhir.Serialization.Tests/StreamXmlResources.cs
Update develop-r4 from develop-stu3
> Update develop-r4 from develop-stu3

- src/Hl7.Fhir.Serialization.Tests/StreamXmlResources.cs
Update develop-r5 from develop-r4
> Update develop-r5 from develop-r4

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/Hl7.Fhir.Core/Model/OperationOutcome.cs
- src/fhir-net-api.props
Address #1529 .
I'm hesitant write tests to it, since I couldn't find any for similar scenario, and in general it feels like a bit painful thing to do, so I just did manual testing.
> Check for null value in _Details to prevent null exception.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/Hl7.Fhir.Core/Model/OperationOutcome.cs
- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/TestData/TestSd/MyCustomResource.StructureDefinition.xml
- src/Hl7.Fhir.Specification/Specification/Terminology/OperationValidCodeExtensions.cs
> Forward merge from develop-stu3 -> develop-r4

- src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
- src/Hl7.Fhir.Specification/Schema/Binding.cs
> fix: proper error messages for codings and codeableconcepts in validator.

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> STU3: fix: remove type specific constraints from polymorph elements

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> R4: fix: remove type specific constraints from polymorph elements

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- build/azure-pipelines.yml
resolves #1554 
Also adding extra instructions for creating issues (link to [discussion](https://github.com/FirelyTeam/firely-net-sdk/discussions))
> Add Azure pipeline

- src/Hl7.Fhir.Core/FhirPath/ElementNavFhirExtensions.cs
This fix was already done in branch develop-r4. Also in that branch the unittest resides.
> #1580: fix to handle as Date

- build/DownloadFhirBuildProfile.ps1
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
> R4: remove dataelements from specifications.zip

- build/DownloadFhirBuildProfile.ps1
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/ConformanceSourceTests.cs
> STU3: Remove dataelements from specifications.zip 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- build/azure-pipelines.yml
- src/Hl7.Fhir.Core.Tests/Rest/SearchParamsTests.cs
- src/Hl7.Fhir.Core/FhirPath/ElementNavFhirExtensions.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
- src/Hl7.Fhir.Specification/Schema/Binding.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathExtensionsTest.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathTest.cs
Forward merge from develop-r4 to develop-r5
> R5: update develop-r5 with develop-r4

- build/azure-pipelines.yml
- src/firely-net-sdk.props
> fix: Adding debug symbols to NuGet/MyGet

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
> STU3: Throwing Exception when snapshot choicetypes are not a subset of base

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
> R4 : Throwing Exception when snapshot choicetypes are not a subset of base 

- src/Hl7.Fhir.Specification/Specification/Terminology/LocalTerminologyService.cs
> LocalTerminologyService: Adding ConfigureAwait(false) at async calls

- README.md
Change documentation link to new sub project structure
> Update docs link in readme.md

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
> Fix Verification of FHIR version of FhirClient

- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/TestData/TestSd/BasicWithTel-StructureDefinition-R4.json
- src/Hl7.Fhir.ElementModel.Tests/TestData/TestSd/TEL.xml
> Fix/1606: TypedElementOnSourceNode logical model data type (for STU3)

- README.md
- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.ElementModel.Tests/ElementNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/TestData/TestSd/BasicWithTel-StructureDefinition-R4.json
- src/Hl7.Fhir.ElementModel.Tests/TestData/TestSd/TEL.xml
- src/Hl7.Fhir.Specification/Specification/Terminology/LocalTerminologyService.cs
Sync recent minor changes from R3 into R4.
> Merge R3 changes into R4

- src/Hl7.Fhir.Core/Model/StructureDefinition.cs
> Fix DebuggingDisplays of ResourceIdentity

- build/RetrieveVersion.ps1
- build/UpdateVersion.ps1
- build/azure-pipelines.yml
- build/finish-release.ps1
- build/forward-merge.ps1
- build/start-develop.ps1
- build/start-release.ps1
- build/templates/apply-versioning-steps-template.yml
- pull_request_template.md
> New Powershell scripts to create and finish a release  

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
> Support relative URLs when parsing HttpResponseMessage to EntryResponse

- src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ExternalTerminologyService.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValidateCodeParameters.cs
> Input parameters for TerminologyService are checked for duplicates

- README.md
- build/RetrieveVersion.ps1
- build/UpdateVersion.ps1
- build/azure-pipelines.yml
- build/finish-release.ps1
- build/forward-merge.ps1
- build/start-develop.ps1
- build/start-release.ps1
- build/templates/apply-versioning-steps-template.yml
- pull_request_template.md
- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Serialization/BaseFhirSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
- src/Hl7.Fhir.ElementModel.Tests/ScopedNodeTests.cs
- src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
- src/Hl7.Fhir.Specification.Tests/StructureDefinitionWalkerTests.cs
- src/Hl7.Fhir.Specification.Tests/TestData/validation/observation-profile-for-discriminator-test.xml
- src/Hl7.Fhir.Specification.Tests/TestData/validation/patient-sliced-complex-extension.xml
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ExternalTerminologyService.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValidateCodeParameters.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DiscriminatorBucket.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ExistsDiscriminator.cs
Update develop-r4 with the latest version of develop-stu3 (forward merge)
> Update develop-r4 with develop-stu3 for release 3.1

- README.md
- build/RetrieveVersion.ps1
- build/UpdateVersion.ps1
- build/azure-pipelines.yml
- build/finish-release.ps1
- build/forward-merge.ps1
- build/start-develop.ps1
- build/start-release.ps1
- build/templates/apply-versioning-steps-template.yml
- pull_request_template.md
- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Serialization/BaseFhirSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirJsonSerializer.cs
- src/Hl7.Fhir.Core/Serialization/FhirXmlSerializer.cs
- src/Hl7.Fhir.ElementModel.Tests/ScopedNodeTests.cs
- src/Hl7.Fhir.Specification.Tests/DiscriminatorInterpreterTests.cs
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
- src/Hl7.Fhir.Specification.Tests/StructureDefinitionWalkerTests.cs
- src/Hl7.Fhir.Specification.Tests/TestData/validation/observation-profile-for-discriminator-test.xml
- src/Hl7.Fhir.Specification.Tests/TestData/validation/patient-sliced-complex-extension.xml
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ExternalTerminologyService.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/ValidateCodeParameters.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DiscriminatorBucket.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ExistsDiscriminator.cs
Update develop-r5 with the latest version of develop-r4 (forward merge)
> Update develop-r5 with develop-r4 for release 3.1

- src/Hl7.Fhir.Specification.Tests/Source/TerminologyTests.cs
- src/Hl7.Fhir.Specification/Specification/Terminology/OperationValidCodeExtensions.cs
> Correct construction of Terminology service output

- build/azure-pipelines.yml
- build/finish-release.ps1
- build/start-develop.ps1
- build/start-release.ps1
We did not take release 4B into account in the scripts for releasing
> Scripts updated with release 4B

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
> Use improved regex for validating Markdown

- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Serialization/BaseFhirParser.cs
> Add backward compatibility to parse datetime for date fields

- build/azure-pipelines.yml
- build/templates/test-job-template.yml
Using a variable from another stage did not work. As a result of that a whole test project (FhirPath R4) did not run
> Devops: fixing pipeline, because a whole testproject did not run 

- build/azure-pipelines.yml
Publishing of Hl7.FhirPath.R4.Tests is now conditional in Azure Pipelines
> Devops: Publishing of Hl7.FhirPath.R4.Tests is now conditional

- build/azure-pipelines.yml
- build/templates/test-job-template.yml
- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core.Tests/Serialization/SerializationTests.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/Hl7.Fhir.Core/Serialization/BaseFhirParser.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
Forward merge from develop-stu3 to develop-r4
> Update develop-r4 with develop-stu3

- src/Hl7.Fhir.Core.Tests/Model/DeepMatchTest.cs
> Fix IDeepcomparable for empty repeating elements in patterns

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> Correctly merge children of value[x] types [R4]

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> Correctly merge children of value[x] types [STU3]

- build/azure-pipelines.yml
Use previous and current tag for creating release notes
> Devops: using previous and current tag for creating release notes

- src/Hl7.Fhir.Core/Hl7.Fhir.Core.csproj
- src/Hl7.Fhir.Specification/Hl7.Fhir.Specification.csproj
> Cleaned up package references

- Hl7.Fhir.sln
- src/Benchmarks/Benchmarks.csproj
- src/Benchmarks/ModelInspectorBenchmarks.cs
- src/Benchmarks/Program.cs
- src/Hl7.Fhir.Core/Model/ModelInfo.cs
- src/firely-net-sdk-tests.props
- src/firely-net-sdk.props
Added benchmark project, and included benchmark test for ModelInspector
> Changes to ClassMapping to support new serializer (for R3-R5)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- LICENSE
- build/templates/test-job-template.yml
Some non coding changes, like:
- adding a remark about Firely Server Facade  in the issue and feature templates
- layout of LICENSE file has changed. The content is still the same.
- Azure pipeline: removed unused parameters
See also the PR on common: https://github.com/FirelyTeam/firely-net-common/pull/146
> Non coding changes (templates, License, pipeline)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- LICENSE
- build/templates/test-job-template.yml
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/validation/profile-communication.xml
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/BucketFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ComprehensiveDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
Update develop-r4B with develop-r4
> Update develop-r4B with develop-r4

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- LICENSE
- build/templates/test-job-template.yml
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/validation/profile-communication.xml
- src/Hl7.Fhir.Specification.Tests/Validation/SliceValidationTests.cs
- src/Hl7.Fhir.Specification.Tests/Validation/TestProfileArtifactSource.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/BucketFactory.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/ComprehensiveDiscriminator.cs
- src/Hl7.Fhir.Specification/Validation/Slicing/DisciminatorFactory.cs
Update develop-r5 with develop-r4B
> Update develop-r5 with develop-r4B

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ProfileNavigationExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> Use Element as primary data type for polymorphic elements [R4]

- src/Hl7.Fhir.Core.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Core/Model/Initializers.cs
> Add fluent HumanName initializers for prefix and suffix

- src/Hl7.Fhir.Specification.Tests/Validation/BindingValidationTests.cs
> Add expansion of currencies valueset to specification.zip [R4]

- src/Hl7.Fhir.Core/Model/IConformanceResource.cs
`CompartmentDefinition` is now a `IVersionableConformanceResource`
Resolves #1902
None
> CompartmentDefinition is now a IVersionableConformanceResource

- src/Hl7.Fhir.ElementModel.Tests/SourceNodeTests.cs
We use now `LazyInitializer.EnsureInitialized` to reduces the amount of memory on `DomNode<T>` (and so `SourceNode` and `ElementNode`)
Resolves #1912.
Resolves #1913 
The unit test NoLazyObjectsAnymore will prove that those objects are not created
> DomNode is not using Lazy<T> anymore to reduce the memory footprint

- build/DownloadFhirBuildProfile.ps1
Forward merge branch `develop-r4B` -> `develop-r5`
> Forward merge branch to develop-r5 with develop-r4B

- src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
- src/Hl7.Fhir.Specification/Validation/ValidationSettings.cs
> Add setting to ignore a custom list of constraints in the validator - STU3

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
Update develop-stu3 -> release/4.0.0-beta1-stu3
> Update develop-stu3 -> release/4.0.0-beta1-stu3

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/firely-net-sdk.props
Update release/4.0.0-beta1-r4 with release/4.0.0-beta1-stu3
> Update release/4.0.0-beta1-r4 with release/4.0.0-beta1-stu3

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/Issue-1981-Patient.StructureDefinition.xml
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Forward merge of branch `develop-stu3` to branch `develop-r4`
> Forward merge of develop-stu3 -> develop-r4

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/Issue-1981-Patient.StructureDefinition.xml
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Forward merge of branch `develop-r4` to branch `develop-r4B`
> Forward merge of develop-r4-> develop-r4B

- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-1981/Issue-1981-Patient.StructureDefinition.xml
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Forward merge of branch `develop-r4B` to branch `develop-r5`
> Forward merge of develop-r4B-> develop-r5

- src/firely-net-sdk.props
Added [Source Link](https://github.com/dotnet/sourcelink#source-link) for enabling anyone building NuGet libraries to provide source debugging. 
PR https://github.com/FirelyTeam/firely-net-common/pull/194
> Added Source Link

- .github/workflows/AddIssuesToProject.yml
Adds a new created issue automatically to the project board
> Use a workflow for automatic add issues to the project

- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/ProfileNavigationTest.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ElementDefinitionNavigator.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/ProfileReference.cs
- src/Hl7.Fhir.Specification/Specification/Navigation/StructureDefinitionWalker.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/Hl7.Fhir.Specification/Specification/Source/ResourceResolverExtensions.cs
- src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
- src/Hl7.Fhir.Specification/Validation/ElementDefinitionNavigatorExtensions.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
> Handle and generate absolute contentRefernces

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
- src/firely-net-sdk.props
Update branch `4.0.0-r4` with branch `4.0.0-stu3`
> Update 4.0.0-r4 with 4.0.0-stu3 (prepare for release)

- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
> Check for null reference when trying to use a FHIR operation without a body [stu3]

- README.md
- build/DownloadFhirBuildProfile.ps1
- src/Hl7.Fhir.Serialization.Tests/RoundtripTest.cs
- src/Hl7.Fhir.Specification.Tests/Source/ArtifactSummaryTests.cs
During the update of R4B (version 4.3.0) I made some changes that should be propagate to all versions.
> Backport some general changes coming from the update R4B (4.3.0)

- src/Hl7.Fhir.Specification.Tests/Source/FhirPackageSourceTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/FhirPackageSource.cs
> Added factory method for creating a FHIR core package source  [STU3]

- src/Hl7.Fhir.Specification.Tests/Source/FhirPackageSourceTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/FhirPackageSource.cs
fixes https://github.com/FirelyTeam/firely-net-sdk/issues/2133
> Added factory method for creating a FHIR Core Package source  [R4]

- src/Hl7.Fhir.Specification.Tests/Source/FhirPackageSourceTests.cs
- src/Hl7.Fhir.Specification/Specification/Source/FhirPackageSource.cs
> Added factory method for creating a FHIR Core Package source [R4B]

- .github/dependabot.yml
- README.md
- build/azure-pipelines.yml
- src/Hl7.Fhir.Core.Tests/Hl7.Fhir.Core.Tests.csproj
- src/Hl7.Fhir.Core.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Core.Tests/TestDataHelper.cs
- src/Hl7.Fhir.Core.Tests/Validation/SearchDataExtraction.cs
- src/Hl7.Fhir.Core.Tests/Validation/ValidationTests.cs
- src/Hl7.Fhir.Core/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Core/Rest/FhirClientSearch.cs
- src/Hl7.Fhir.Serialization.Tests/RoundtripTest.cs
- src/Hl7.Fhir.Serialization.Tests/StreamXmlResources.cs
- src/Hl7.Fhir.Specification.Tests/Hl7.Fhir.Specification.Tests.csproj
- src/Hl7.Fhir.Specification.Tests/Snapshot/ElementDefinitionPropertyProxy.cs
- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementDefnMerger.cs
- src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryExtensions.cs
- src/Hl7.Fhir.Specification/Specification/Source/Summary/ArtifactSummaryPropertyBag.cs
- src/Hl7.Fhir.Specification/Specification/Source/ZipCacher.cs
- src/Hl7.Fhir.Specification/Specification/StructureDefinitionSummaryProvider.cs
- src/firely-net-sdk-tests.props
Update `develop-r4B` with `develop-r4`
> Update `develop-r4B` with `develop-r4`

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
- src/firely-net-sdk.props
> [SnapshotGenerator] Remove redundant type slices [STU3]

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/ElementMatcher.cs
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> [SnapshotGenerator] Remove redundant type slices [R4]

- src/Hl7.Fhir.ElementModel.Tests/ScopedNodeTests.cs
- src/Hl7.Fhir.ElementModel.Tests/TestData/bundle-contained-references.xml
- src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
Test the new resolve("#") functionality in common.
> 1688 - Add functionality to have "#" resolve to container (STU3)

- src/Hl7.Fhir.Core.Tests/ElementModel/PocoTypedElementTests.cs
- src/Hl7.Fhir.Core/FhirPath/FhirPathExtensions.cs
Changes the POCO FhirPath extensions so they install the FHIR specific functions.
> 1968 Add FHIR FP dialect functions for POCO extension methods

- src/Hl7.Fhir.Specification.Tests/Validation/ProfileAssertionTests.cs
- src/Hl7.Fhir.Specification/Validation/ProfileAssertion.cs
- src/Hl7.Fhir.Specification/Validation/ProfilePreprocessor.cs
- src/Hl7.Fhir.Specification/Validation/Validator.cs
Turned resolution errors into warnings IF we are in an extension - not a modifierExtension
> 2114 Unresolvable extensions should produce warnings

- src/Hl7.Fhir.Core.Tests/ElementModel/PocoTypedElementTests.cs
> 2018 Make sure repeats() does not hang when given a constant argument

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
Improvement of the following invariants:
- ref-1
- sdf-24 
- sdf-25
And add an unit test to prove it.
Resolves #2153 
See `BasicValidationTests.InvariantValidation`
> Improvement of invariants ref-1, sdf-24 and sdf-25 [STU3]

- src/Hl7.Fhir.Specification.Tests/Validation/BasicValidationTests.cs
- src/Hl7.Fhir.Specification/Validation/FpConstraintValidationExtensions.cs
Improvement of the following invariants:
- ref-1
- sdf-24 
- sdf-25
And add an unit test to prove it.
Resolves #2153 
See `BasicValidationTests.InvariantValidation`
> Improvement of invariants ref-1, sdf-24 and sdf-25 [R4B]

- src/Hl7.Fhir.Core.Tests/Validation/SearchDataExtraction.cs
- src/Hl7.Fhir.Core/FhirPath/FhirPathExtensions.cs
> Backport changes from R4

- src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-2211/ObservationBaseLimitedChoiceTypes.xml
- src/Hl7.Fhir.Specification.Tests/TestData/snapshot-test/Issue-2211/ObservationDerivedLimitedChoiceTypes.xml
- src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
> [SnapshotGenerator] Do removals in snapshot generation after all other actions. [R4]

- src/Hl7.Fhir.Core.Tests/Validation/ValidationTests.cs
> Remove rule on DomainResource that contained resources cannot have narrative

- src/Hl7.Fhir.Specification.Tests/Validation/IssuesTests.cs
Remove the unnecessary sliceName in the unit test ` Issue2183TypeCheck`.
> Merge  backwards of R4

- src/Hl7.Fhir.Base/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Base/Utility/SemVersion.cs
- src/Hl7.Fhir.STU3.Tests/Model/ModelTests.cs
- src/Hl7.Fhir.Shims.STU3AndUp/Model/ModelInfo.cs
Also made SemVersion internal instead of public
> Remove  CheckMinorVersionCompatibility functionality out of ModelInfo

- src/Hl7.Fhir.Base/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Base/Rest/FhirClientOperations.cs
- src/Hl7.Fhir.Base/Rest/FhirClientSearch.cs
- src/Hl7.Fhir.Base/Rest/HttpClientRequester.cs
- src/Hl7.Fhir.Conformance/Specification/Source/CommonWebResolver.cs
- src/Hl7.Fhir.STU3.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.STU3.Tests/Rest/OperationsTests.cs
- src/Hl7.Fhir.STU3.Tests/Rest/ReadAsyncTests.cs
- src/Hl7.Fhir.STU3.Tests/Rest/SearchAsyncTests.cs
- src/Hl7.Fhir.STU3/Specification/Source/WebResolver.cs
- src/Hl7.Fhir.Shared.Tests/Rest/FhirClientMockTests.cs
- src/Hl7.Fhir.Shared.Tests/Rest/FhirClientTests.cs
- src/Hl7.Fhir.Shared.Tests/Rest/OperationsTests.cs
- src/Hl7.Fhir.Shared.Tests/Rest/ReadAsyncTests.cs
- src/Hl7.Fhir.Shared.Tests/Rest/SearchAsyncTests.cs
- src/Hl7.Fhir.Shims.STU3AndUp/Rest/FhirClientOperationsExtensions.cs
- src/Hl7.FhirPath.R4.Tests/PocoTests/FhirPathEvaluatorTest.cs
Added a CancellationToken parameter to all FhirClient operations.
Obsoleted non-async calls.
Fixed #2024.
> Add CancellationToken support

- src/Benchmarks/Benchmarks.csproj
- src/Hl7.Fhir.Base/Hl7.Fhir.Base.csproj
- src/firely-net-sdk-tests.props
Bumped package dependencies, suggested by dependencybot
> Upgrading package dependencies

- src/Hl7.Fhir.Base/Utility/EnumUtility.cs
- src/Hl7.Fhir.Support.Tests/Utility/EnumMappingTest.cs
> 2338 Fix nullref exception in EnumUtility

- src/Hl7.Fhir.Base/Introspection/PropertyMapping.cs
- src/Hl7.Fhir.Base/Introspection/ReferencesAttribute.cs
- src/Hl7.Fhir.Base/Model/Generated/Signature.cs
- src/Hl7.Fhir.Base/Serialization/BaseFhirJsonPocoDeserializer.cs
- src/Hl7.Fhir.Base/Serialization/BaseFhirJsonPocoSerializer.cs
- src/Hl7.Fhir.Base/Serialization/BaseFhirXmlPocoDeserializer.cs
- src/Hl7.Fhir.Base/Serialization/DispatchingReader.cs
- src/Hl7.Fhir.Serialization.R4.Tests/RoundtripSignature.cs
- src/Hl7.Fhir.Serialization.STU3.Tests/RoundtripSignature.cs
> 2373 Added support elements that have changed from choice to non-choice.

- build/build-variables.yml
- build/templates/test-job-template.yml
- src/firely-net-sdk-tests.props
- src/firely-net-sdk.props
* Changed the props and build pipeline to support C# 11 features.
* Also cleaned up the remaining net4.0 clauses in tests.props.
> Update to C# 11

- src/Hl7.Fhir.Base/Specification/Terminology/ITerminologyService.cs
- src/Hl7.Fhir.Base/Specification/Terminology/MultiTerminologyService.cs
- src/Hl7.Fhir.Support.Tests/Specification/MultiTerminologyServiceTests.cs
> Added MultiTerminologyService

- src/Hl7.Fhir.Base/Specification/Terminology/MimeTypeTerminologyService.cs
- src/Hl7.Fhir.Support.Tests/Specification/MimeTypeTerminologyServiceTests.cs
Also support versioned valueset canonicals
fixes #2502
fixes #2504
> Support STU3 mime type vs url in MimeTypeTerminologyService

- src/Hl7.Fhir.Conformance/Specification/Snapshot/ElementDefnMerger.cs
> Support new R5 elements in snapshot generator

- src/Hl7.Fhir.Base/ElementModel/SourceNodeComparator.cs
- src/Hl7.Fhir.ElementModel.Shared.Tests/SourceNodeTests.cs
> Add missing returns to SourceNodeComparator

- src/Hl7.Fhir.Base/ElementModel/SourceNodeComparator.cs
- src/Hl7.Fhir.ElementModel.Shared.Tests/SourceNodeTests.cs
> Missed another return in SourceNodeComparator

- src/Hl7.Fhir.Base/ElementModel/TypedElementExtensions.cs
- src/Hl7.Fhir.Base/FhirPath/Functions/EqualityOperators.cs
- src/Hl7.Fhir.Support.Tests/ElementModel/TypedElementExtensionTests.cs
Aligned with what FhirPath does (minus the FhirPath conversion).
Fixes #2431.
> Improved the comparison between "primitive" ITypedElement nodes

- src/Hl7.Fhir.Base/Rest/BaseFhirClient.cs
- src/Hl7.Fhir.Support.Poco.Tests/Rest/FhirClientMockTests.cs
> Allow all 2xx http response codes for FHIR operations

- src/Hl7.Fhir.Base/Rest/SearchParams.cs
- src/Hl7.Fhir.Support.Poco.Tests/Rest/SearchParamsTests.cs
Fixes #2686.
Also refreshed the code, documented, enabled nullability.
> The `_count` parameter should allow '0' as a value
